const localOrigin = `http://127.0.0.1:${process.env.PLAYWRIGHT_PORT || '5174'}`
import { expectModal } from './helpers.js'
import { navigate } from './helpers.js'
import { openMenu, tabTo } from './helpers.js'
import { test, expect } from '@playwright/test'
import { task, seed, rows, row, checkbox, edit, save, saved, raw, writes, ids, filter, fillDraft, expectFocusFits } from './helpers.js'

const step = (page, title, action = 'Legg til neste steg') => row(page, title).getByRole('button', { name: `${action} «${title}»`, exact: true })
const work = (page, title) => row(page, title).getByRole('checkbox', { name: `Ferdig med arbeidet «${title}»`, exact: true, includeHidden: true })
const delivery = (page, title, undo = false) => row(page, title).getByRole('button', { name: `${undo ? 'Angre levering' : 'Bekreft levert'} «${title}»`, exact: true })
const saveStep = page => page.locator('#step-form').getByRole('button', { name: 'Lagre neste steg', exact: true })
const visibleRows = page => page.locator('#task-list li:visible')

async function fillStep(page, description = 'Les oppgaveteksten og lag en disposisjon', minutes = '20') {
  await page.getByLabel('Beskrivelse av neste steg', { exact: true }).fill(description)
  await page.getByLabel('Estimat for neste steg (minutter)', { exact: true }).fill(minutes)
}

test('new submission task and one validated next step persist through edit, reload and reopen', async ({ page, context }, testInfo) => {
  await seed(page, [])
  await page.locator('#new-task').click()
  await fillDraft(page, { title: 'Skriv rapport i IBE160', course: 'IBE160', deadlineLocal: '2026-09-03T15:00', estimatedMinutes: '240' })
  await page.getByRole('checkbox', { name: 'Krever innlevering', exact: true }).check()
  await save(page).click()
  const title = 'Skriv rapport i IBE160'
  await expect(work(page, title)).not.toBeChecked()
  await openMenu(page, title)
  await step(page, title).click()
  const beforeStep = await raw(page)
  for (const minutes of ['', '0', '-1']) {
    await fillStep(page, 'Les oppgaveteksten', minutes)
    await saveStep(page).click()
    await expect(page.locator('#step-estimatedMinutes')).toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator('#step-estimatedMinutes')).toBeFocused()
    await expect(page.locator('#step-description')).toHaveValue('Les oppgaveteksten')
    expect(await raw(page)).toBe(beforeStep)
    expect(await writes(page)).toHaveLength(1)
  }
  await fillStep(page, ' ', '20')
  await saveStep(page).click()
  await expect(page.locator('#step-description')).toHaveAttribute('aria-invalid', 'true')
  await expect(page.locator('#step-description')).toBeFocused()
  expect(await raw(page)).toBe(beforeStep)
  await fillStep(page)
  await saveStep(page).click()
  await expect(page.locator('#step-form')).toBeHidden()
  await expect(row(page, title)).toContainText('Les oppgaveteksten og lag en disposisjon')
  await expect(row(page, title)).toContainText('20 min · bare neste steg')
  await expect(row(page, title)).toContainText('Gjenstående arbeid: 240 min')
  await openMenu(page, title)
  await edit(page, title).click()
  await expect(page.locator('#requiresSubmission')).toBeChecked()
  await page.locator('#course').fill('IBE160 – rapport')
  await save(page).click()
  const expected = await saved(page)
  expect(expected.tasks[0]).toMatchObject({
    title, course: 'IBE160 – rapport', estimatedMinutes: null, remainingMinutes: 240, completed: false, requiresSubmission: true,
    nextStep: { description: 'Les oppgaveteksten og lag en disposisjon', estimatedMinutes: 20 },
  })
  expect(expected.tasks[0].submitted).not.toBe(true)
  await page.reload()
  await navigate(page, 'week')
  await expect(row(page, title)).toContainText('20 min · bare neste steg')
  expect(await saved(page)).toEqual(expected)
  expect(await writes(page)).toEqual([])
  await page.close()
  const reopened = await context.newPage()
  await reopened.goto('/')
  await navigate(reopened, 'all')
  await expect(row(reopened, title)).toContainText('Les oppgaveteksten og lag en disposisjon')
  expect(await saved(reopened)).toEqual(expected)
})

test('edit, remove and complete a next step leave parent estimate, completion and delivery unchanged', async ({ page }, testInfo) => {
  const parent = { ...task('report', '2026-09-03T15:00', 240), requiresSubmission: true,
    nextStep: { description: 'Les oppgaveteksten', estimatedMinutes: 20 } }
  await seed(page, [parent])
  await openMenu(page, parent.title)
  await step(page, parent.title, 'Rediger neste steg').click()
  await expect(page.locator('#step-description')).toHaveValue('Les oppgaveteksten')
  await fillStep(page, 'Lag en disposisjon', '15')
  await saveStep(page).click()
  expect((await saved(page)).tasks[0].nextStep).toEqual({ description: 'Lag en disposisjon', estimatedMinutes: 15 })
  await expect(step(page, parent.title, 'Rediger neste steg')).toHaveCount(1)
  await expect(step(page, parent.title)).toHaveCount(0)
  await openMenu(page, parent.title)
  await step(page, parent.title, 'Fjern neste steg').click()
  const { nextStep: removedStep, ...withoutStep } = parent
  expect(removedStep.estimatedMinutes).toBe(20)
  expect((await saved(page)).tasks[0]).toEqual(withoutStep)
  await openMenu(page, parent.title)
  await step(page, parent.title).click()
  await fillStep(page, 'Finn to kilder', '10')
  await saveStep(page).click()
  await openMenu(page, parent.title)
  await step(page, parent.title, 'Neste steg gjort').click()
  expect((await saved(page)).tasks[0]).toEqual(withoutStep)
  await expect(work(page, parent.title)).not.toBeChecked()
  await expect(row(page, parent.title)).toContainText('Hele oppgaven: 240 min')
  await openMenu(page, parent.title)
  await step(page, parent.title).click()
  await fillStep(page, 'Skriv innledningen', '25')
  await saveStep(page).click()
  await page.reload()
  await navigate(page, 'week')
  expect((await saved(page)).tasks[0]).toEqual({ ...withoutStep, nextStep: { description: 'Skriv innledningen', estimatedMinutes: 25 } })
  await expect(work(page, parent.title)).not.toBeChecked()
})

test('one explained main suggestion uses remaining work, deadline order and optional alternatives without writes', async ({ page }, testInfo) => {
  const earliest = { ...task('step-first', '2026-09-03T11:00', 240), remainingMinutes: 20,
    nextStep: { description: 'Lag rapportdisposisjonen', estimatedMinutes: 20 } }
  const fallback = task('whole-task', '2026-09-03T13:00', 30)
  const future = { ...task('future-step', '2026-09-10T12:00', 300), remainingMinutes: 25, nextStep: { description: 'Les første side', estimatedMinutes: 10 } }
  const blockedByStep = { ...task('step-too-long', '2026-09-03T09:00', 10), splittable: false, remainingMinutes: 60, nextStep: { description: 'Les hele kapitlet', estimatedMinutes: 31 } }
  const large = { ...task('overdue-large', '2026-09-03T08:00', 240), splittable: false }
  const ready = { ...task('ready', '2026-09-03T07:00', 10, true), requiresSubmission: true }
  const candidates = [fallback, future, blockedByStep, large, ready, earliest]
  await seed(page, candidates)
  const before = await raw(page)
  await filter(page, '30', { alternatives: false })
  expect(await ids(page)).toEqual([earliest.id, fallback.id, future.id])
  await expect(visibleRows(page)).toHaveCount(1)
  await expect(visibleRows(page)).toHaveAttribute('data-task-id', earliest.id)
  await expect(row(page, earliest.title)).toContainText(/hovedforslag/i)
  await expect(row(page, earliest.title)).toContainText('Lag rapportdisposisjonen')
  await expect(row(page, earliest.title)).toContainText('20 min · bare neste steg')
  await expect(row(page, earliest.title)).toContainText('3. september kl. 11:00')
  await expect(row(page, earliest.title)).toContainText(/Passer innen 30 minutter.*forfalt frist/)
  const alternatives = page.getByRole('button', { name: 'Vis alternativer (2)', exact: true })
  await expect(alternatives).toHaveAttribute('aria-expanded', 'false')
  await alternatives.focus()
  await page.keyboard.press('Enter')
  await expect(visibleRows(page)).toHaveCount(3)
  await expect(page.locator('#toggle-alternatives')).toHaveAttribute('aria-expanded', 'true')
  await expect(row(page, fallback.title)).toContainText('Hele oppgaven: 30 min')
  await page.keyboard.press('Shift+Tab')
  await expect(row(page, future.title).locator('.task-menu > summary')).toBeFocused()
  await page.keyboard.press('Enter')
  await tabTo(page, step(page, future.title, 'Fjern neste steg'))
  await tabTo(page, page.locator('#toggle-alternatives'))
  await page.keyboard.press('Enter')
  await expect(visibleRows(page)).toHaveCount(1)
  await expect(page.locator('#toggle-alternatives')).toBeFocused()
  await navigate(page, 'week')
  for (const item of [earliest, fallback, blockedByStep, large, ready]) await expect(row(page, item.title)).toBeVisible()
  await expect(row(page, large.title).getByText('Forfalt', { exact: true })).toBeVisible()
  await expect(row(page, ready.title)).toContainText('Klar til levering')
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
})

test('empty time results keep all deadlines and next-step editing reachable without treating a short step as remaining work', async ({ page }, testInfo) => {
  const large = { ...task('large', '2026-09-03T10:00', 240), splittable: false }
  const later = { ...task('later', '2026-09-03T16:00', 120), splittable: false }
  await seed(page, [later, large])
  await filter(page, '20', { alternatives: false })
  await expect(visibleRows(page)).toHaveCount(0)
  await expect(page.locator('#empty-tasks')).toContainText('Ingen oppgaver passer tiden')
  await expect(page.locator('#empty-minutes')).toBeVisible()
  await page.locator('#empty-all').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#view-all')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#view-all')).toBeFocused()
  await expect(row(page, large.title)).toBeVisible()
  await expect(row(page, later.title)).toBeVisible()
  await tabTo(page, row(page, large.title).locator('.task-menu > summary'))
  if (!await row(page, large.title).locator('.task-menu').evaluate(element => element.open)) await page.keyboard.press('Enter')
  await tabTo(page, step(page, large.title))
  expect(await writes(page)).toEqual([])
  await page.keyboard.press('Enter')
  await fillStep(page, 'Åpne oppgaveteksten og les kravene', '20')
  await saveStep(page).click()
  await filter(page, '20', { alternatives: false })
  await expect(visibleRows(page)).toHaveCount(1)
  await expect(row(page, large.title)).toContainText('20 min · bare neste steg')
  await expect(row(page, large.title)).toContainText('Hele oppgaven er ikke ferdig etter steget')
  await navigate(page, 'all')
  await expect(row(page, large.title)).toContainText('Åpne oppgaveteksten og les kravene')
  expect((await saved(page)).tasks).toEqual([later, { ...large, nextStep: { description: 'Åpne oppgaveteksten og les kravene', estimatedMinutes: 20 } }])
  expect(await writes(page)).toHaveLength(1)
})

test('work completion and confirmed delivery are separate, reversible states with ready work still due', async ({ page }, testInfo) => {
  const submission = { ...task('submission', '2026-09-03T11:59', 20), requiresSubmission: true }
  const ordinary = task('reading', '2026-09-03T15:00', 15)
  await seed(page, [submission, ordinary])
  await openMenu(page, submission.title)
  await work(page, submission.title).check()
  await expect(row(page, submission.title)).toContainText('Klar til levering')
  await expect(row(page, submission.title).getByText('Forfalt', { exact: true })).toBeVisible()
  expect((await saved(page)).tasks[0].submitted).not.toBe(true)
  await filter(page, '30', { alternatives: false })
  expect(await ids(page)).toEqual([ordinary.id])
  await expect(row(page, ordinary.title)).toContainText(/hovedforslag/i)
  await expect(row(page, ordinary.title)).toContainText(/Passer innen 30 minutter.*nærmeste frist/)
  await navigate(page, 'week')
  await expect(row(page, submission.title)).toBeVisible()
  await openMenu(page, submission.title)
  await delivery(page, submission.title).click()
  expect((await saved(page)).tasks[0]).toMatchObject({ completed: true, submitted: true })
  await expect(row(page, submission.title)).toContainText('Levert')
  await expect(row(page, submission.title).getByText('Forfalt', { exact: true })).toBeHidden()
  await expect(work(page, submission.title)).toBeDisabled()
  await openMenu(page, submission.title)
  await edit(page, submission.title).click()
  await expect(page.locator('#requiresSubmission')).toBeChecked()
  await expect(page.locator('#requiresSubmission')).toBeDisabled()
  await page.locator('#cancel-task').click()
  await page.reload()
  await navigate(page, 'week')
  await expect(row(page, submission.title)).toContainText('Levert')
  await openMenu(page, submission.title)
  await delivery(page, submission.title, true).click()
  await expect(row(page, submission.title)).toContainText('Klar til levering')
  expect((await saved(page)).tasks[0]).toMatchObject({ completed: true, submitted: false })
  await openMenu(page, submission.title)
  await work(page, submission.title).uncheck()
  expect((await saved(page)).tasks[0]).toMatchObject({ completed: false, submitted: false, remainingMinutes: null })
  await openMenu(page, submission.title)
  await edit(page, submission.title).click()
  await page.locator('#remainingMinutes').fill('20')
  await save(page).click()
  await openMenu(page, ordinary.title)
  await checkbox(page, ordinary.title).check()
  await expect(row(page, ordinary.title)).toContainText('Fullført')
  await expect(delivery(page, ordinary.title)).toHaveCount(0)
  await filter(page, '30', { alternatives: false })
  expect(await ids(page)).toEqual([submission.id])
})

test('legacy completion never implies delivery and legacy/new data are read without migration writes', async ({ page }, testInfo) => {
  const legacy = task('legacy-completed', '2026-09-03T11:00', 30, true)
  const ready = { ...task('ready-without-confirmation', '2026-09-03T12:00', 40, true), requiresSubmission: true }
  const withStep = { ...task('new-step', '2026-09-03T16:00', 240), splittable: false, nextStep: { description: 'Velg tema', estimatedMinutes: 15 } }
  await seed(page, [legacy, ready, withStep])
  const before = await raw(page)
  await expect(row(page, legacy.title)).toContainText('Fullført')
  await expect(row(page, ready.title)).toContainText('Klar til levering')
  await expect(delivery(page, ready.title)).toBeEnabled()
  await filter(page, '30', { alternatives: false })
  expect(await ids(page)).toEqual([withStep.id])
  await expect(row(page, withStep.title)).toContainText('15 min · bare neste steg')
  await expect(row(page, withStep.title)).toContainText('Hele oppgaven er ikke ferdig etter steget')
  await page.reload()
  await navigate(page, 'week')
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
  await openMenu(page, legacy.title)
  await edit(page, legacy.title).click()
  await expect(page.locator('#requiresSubmission')).not.toBeChecked()
  await page.locator('#requiresSubmission').check()
  await save(page).click()
  await expect(row(page, legacy.title)).toContainText('Klar til levering')
  expect((await saved(page)).tasks[0].submitted).not.toBe(true)
  expect((await saved(page)).tasks.slice(1)).toEqual([ready, withStep])
})

test('failed step save, completion and removal preserve both stored data and the current step until retry', async ({ page }, testInfo) => {
  const parent = task('step-failure', '2026-09-03T15:00', 240)
  await seed(page, [parent])
  await openMenu(page, parent.title)
  await step(page, parent.title).click()
  await fillStep(page, 'Lag en disposisjon', '20')
  const before = await raw(page)
  await page.evaluate(() => { window.failWrite = true })
  await saveStep(page).click()
  expect(await raw(page)).toBe(before)
  await expect(page.locator('#step-form')).toBeVisible()
  await expect(page.locator('#step-description')).toHaveValue('Lag en disposisjon')
  await expect(page.locator('#step-estimatedMinutes')).toHaveValue('20')
  await expect(saveStep(page)).toBeFocused()
  await expect(page.getByRole('status')).toContainText('ikke lagret')
  await page.evaluate(() => { window.failWrite = false })
  await saveStep(page).click()
  for (const action of ['Neste steg gjort', 'Fjern neste steg']) {
    const beforeAction = await raw(page)
    await page.evaluate(() => { window.failWrite = true })
    await openMenu(page, parent.title)
    await step(page, parent.title, action).click()
    expect(await raw(page)).toBe(beforeAction)
    await expect(row(page, parent.title)).toContainText('Lag en disposisjon')
    await expect(checkbox(page, parent.title)).not.toBeChecked()
    await page.evaluate(() => { window.failWrite = false })
  }
  await openMenu(page, parent.title)
  await step(page, parent.title, 'Neste steg gjort').click()
  expect((await saved(page)).tasks).toEqual([parent])
  expect(await writes(page)).toHaveLength(5)
})

test('failed delivery and undo keep the saved confirmation and due status until successful retry', async ({ page }, testInfo) => {
  const ready = { ...task('delivery-failure', '2026-09-03T11:00', 20, true), requiresSubmission: true }
  await seed(page, [ready])
  let before = await raw(page)
  await page.evaluate(() => { window.failWrite = true })
  await openMenu(page, ready.title)
  await delivery(page, ready.title).click()
  expect(await raw(page)).toBe(before)
  await expect(row(page, ready.title)).toContainText('Klar til levering')
  await expect(delivery(page, ready.title)).toBeFocused()
  await page.evaluate(() => { window.failWrite = false })
  await openMenu(page, ready.title)
  await delivery(page, ready.title).click()
  before = await raw(page)
  await page.evaluate(() => { window.failWrite = true })
  await openMenu(page, ready.title)
  await delivery(page, ready.title, true).click()
  expect(await raw(page)).toBe(before)
  await expect(delivery(page, ready.title, true)).toBeVisible()
  await expect(work(page, ready.title)).toBeDisabled()
  await expect(row(page, ready.title).getByText('Forfalt', { exact: true })).toBeHidden()
  await page.evaluate(() => { window.failWrite = false })
  await openMenu(page, ready.title)
  await delivery(page, ready.title, true).click()
  await expect(row(page, ready.title)).toContainText('Klar til levering')
  await expect(row(page, ready.title).getByText('Forfalt', { exact: true })).toBeVisible()
  expect(await writes(page)).toHaveLength(4)
})

test('step dialog contains focus through Monday rollover, cancels without writes and displays HTML-like descriptions as text', async ({ page }, testInfo) => {
  const externalRequests = []
  page.on('request', request => {
    if (new URL(request.url()).origin !== localOrigin) externalRequests.push(request.url())
  })
  const literal = '<img src="https://example.invalid/PRIVATE_STEP_4619" onerror="window.stepTextExecuted=true">'
  const parent = { ...task('step-draft', '2026-09-06T23:59', 240), remainingMinutes: 20,
    nextStep: { description: literal, estimatedMinutes: 20 } }
  await seed(page, [parent], { now: '2026-09-06T23:59:59+02:00' })
  const before = await raw(page)
  await expect(row(page, parent.title)).toContainText(`${literal}`)
  await expect(page.locator('#task-list img, #task-list script')).toHaveCount(0)
  expect(await page.evaluate(() => window.stepTextExecuted)).toBeUndefined()
  await filter(page, '20', { alternatives: false })
  await expect(row(page, parent.title)).toContainText(literal)
  await navigate(page, 'week')
  await openMenu(page, parent.title)
  await step(page, parent.title, 'Rediger neste steg').click()
  await fillStep(page, 'Ulagret nytt steg', '7')
  await expectModal(page, 'step-form')
  for (const control of await rows(page).locator('button, input[type=checkbox]').all()) await expect(control).toBeDisabled()
  await page.locator('#step-description').focus()
  await page.clock.runFor(2000)
  await expect(rows(page)).toHaveCount(0)
  await expect(page.locator('#step-form')).toBeVisible()
  await expect(page.locator('#step-description')).toHaveValue('Ulagret nytt steg')
  await expect(page.locator('#step-description')).toBeFocused()
  await expect(page.locator('#step-estimatedMinutes')).toHaveValue('7')
  await expectModal(page, 'step-form')
  await page.locator('#cancel-step').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#step-form')).toBeHidden()
  await expect(page.locator('#new-task')).toBeFocused()
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
  await navigate(page, 'all')
  await expect(row(page, parent.title)).toContainText(literal)
  await openMenu(page, parent.title)
  await step(page, parent.title, 'Rediger neste steg').click()
  await expect(page.locator('#step-description')).toHaveValue(literal)
  await expect(page.locator('#step-estimatedMinutes')).toHaveValue('20')
  await page.locator('#cancel-step').click()
  await expect(page.locator('#task-list img, #task-list script')).toHaveCount(0)
  expect(await page.evaluate(() => window.stepTextExecuted)).toBeUndefined()
  expect(externalRequests).toEqual([])
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
})

for (const width of [360, 1280]) {
  test(`next step, primary suggestion and delivery controls work with visible keyboard focus at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    const parent = { ...task('keyboard-step', '2026-09-03T11:00', 240), remainingMinutes: 20, requiresSubmission: true }
    await seed(page, [parent])
    await openMenu(page, parent.title)
    await step(page, parent.title).focus()
    await page.keyboard.press('Enter')
    await expectFocusFits(page, page.locator('#step-description'))
    await page.keyboard.type('LangNesteStegBeskrivelse'.repeat(12))
    await page.keyboard.press('Tab')
    await expectFocusFits(page, page.locator('#step-estimatedMinutes'))
    await page.keyboard.type('20')
    await tabTo(page, saveStep(page))
    await expectFocusFits(page, saveStep(page))
    await page.keyboard.press('Tab')
    await expectFocusFits(page, page.locator('#cancel-step'))
    await page.screenshot({ path: testInfo.outputPath(`next-step-form-${width}.png`), fullPage: true })
    await page.keyboard.press('Shift+Tab')
    await page.keyboard.press('Enter')
    await expectFocusFits(page, step(page, parent.title, 'Rediger neste steg'))
    await filter(page, '20', { alternatives: false })
    await expect(visibleRows(page)).toHaveCount(1)
    await tabTo(page, row(page, parent.title).locator('.task-menu > summary'))
    if (!await row(page, parent.title).locator('.task-menu').evaluate(element => element.open)) await page.keyboard.press('Enter')
    await tabTo(page, step(page, parent.title, 'Neste steg gjort'))
    await page.screenshot({ path: testInfo.outputPath(`next-step-suggestion-${width}.png`), fullPage: true })
    await page.keyboard.press('Enter')
    await expect(visibleRows(page)).toHaveCount(1)
    await navigate(page, 'all')
    await tabTo(page, row(page, parent.title).locator('.task-menu > summary'))
    if (!await row(page, parent.title).locator('.task-menu').evaluate(element => element.open)) await page.keyboard.press('Enter')
    await tabTo(page, work(page, parent.title))
    await page.keyboard.press('Space')
    await expectFocusFits(page, work(page, parent.title))
    await tabTo(page, delivery(page, parent.title))
    await page.keyboard.press('Enter')
    await expectFocusFits(page, delivery(page, parent.title, true))
    await page.keyboard.press('Enter')
    await expectFocusFits(page, delivery(page, parent.title))
    await expect(row(page, parent.title)).toContainText('Klar til levering')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`ready-for-delivery-${width}.png`), fullPage: true })
  })
}
