import { expectModal } from './helpers.js'
import { navigate } from './helpers.js'
import { test, expect } from '@playwright/test'
import { task, freeze, instrumentWrites, raw, saved, writes, save, tabTo, expectFocusFits, openMenu, edit, checkbox } from './helpers.js'

const now = '2026-09-07T09:00:00+02:00'
const session = (id, startTime = '10:00', endTime = '11:00', dateLocal = '2026-09-07') => ({ id, dateLocal, startTime, endTime })
const planned = (page, id) => page.locator(`[data-capacity-task="${id}"]`)
const sessionRows = page => page.locator('#session-list > li')
const sessionSave = page => page.locator('#session-form button[type=submit]')
async function setup(page, tasks, sessions) {
  await freeze(page, now)
  await page.goto('/')
  await page.evaluate(({ tasks, sessions }) => localStorage.setItem('studieplanlegger:v1', JSON.stringify({ schemaVersion: 1, tasks, ...(sessions === undefined ? {} : { sessions }) })), { tasks, sessions })
  await instrumentWrites(page)
  await page.reload()
  await navigate(page, 'capacity')
  expect(await writes(page)).toEqual([])
}
async function fillSession(page, date, start, end) {
  await page.locator('#session-dateLocal').fill(date)
  await page.locator('#session-startTime').fill(start)
  await page.locator('#session-endTime').fill(end)
}
async function addSession(page, date, start, end) {
  await page.locator('#new-session').click()
  await fillSession(page, date, start, end)
  await sessionSave(page).click()
}

test('real session controls split remaining parent work, edit and delete saved sessions and preserve old tasks', async ({ page }, testInfo) => {
  const work = { ...task('report', '2026-09-07T13:00', 120), remainingMinutes: 90, nextStep: { description: 'Les innledningen', estimatedMinutes: 20 } }
  await setup(page, [work])
  await expect(planned(page, work.id)).toContainText('Ikke planlagt: 90 min')
  await addSession(page, '2026-09-07', '10:00', '11:00')
  await expect(planned(page, work.id)).toContainText('Satt av: 60 min · Ikke planlagt: 30 min')
  await addSession(page, '2026-09-07', '11:00', '12:00')
  await expect(planned(page, work.id)).toContainText('Satt av: 90 min · Ikke planlagt: 0 min')
  await expect(planned(page, work.id)).toContainText('10:00–11:00: 60 min')
  await expect(planned(page, work.id)).toContainText('11:00–11:30: 30 min')
  await expect(page.locator('#capacity-summary')).toContainText('30 min ledig')
  expect((await saved(page)).tasks).toEqual([work])
  await sessionRows(page).nth(1).getByRole('button', { name: /Rediger studieøkt/ }).click()
  await page.locator('#session-endTime').fill('11:15')
  await sessionSave(page).click()
  await expect(planned(page, work.id)).toContainText('Ikke planlagt: 15 min')
  page.once('dialog', dialog => dialog.accept())
  await sessionRows(page).nth(1).getByRole('button', { name: /Slett studieøkt/ }).click()
  await expect(planned(page, work.id)).toContainText('Ikke planlagt: 30 min')
  await page.reload()
  await navigate(page, 'capacity')
  await expect(sessionRows(page)).toHaveCount(1)
  expect((await saved(page)).tasks).toEqual([work])
  expect(await writes(page)).toEqual([])
})

test('rejects overlaps and invalid times without losing draft; modal and clock preserve draft and focus', async ({ page }, testInfo) => {
  await setup(page, [task('draft', '2026-09-07T12:00', 90)], [session('first')])
  const before = await raw(page)
  await page.locator('#new-session').click()
  await fillSession(page, '2026-09-07', '10:30', '11:30')
  await sessionSave(page).click()
  await expect(page.locator('#session-error')).toContainText(/overlapp/i)
  await expect(page.locator('#session-startTime')).toHaveValue('10:30')
  await expectModal(page, 'session-form')
  await page.locator('#session-startTime').focus()
  await page.clock.runFor(61_000)
  await expect(page.locator('#session-startTime')).toBeFocused()
  await expect(page.locator('#session-startTime')).toHaveValue('10:30')
  await expectModal(page, 'session-form')
  await expect(page.locator('#view-capacity')).toHaveAttribute('aria-pressed', 'true')
  await page.locator('#session-startTime').fill('25:00')
  await sessionSave(page).click()
  await expect(page.locator('#session-error')).not.toBeEmpty()
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
  await page.locator('#cancel-session').click()
  await expect(page.locator('#new-session')).toBeFocused()
  await navigate(page, 'all')
  await navigate(page, 'capacity')
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
})

test('session save and delete failures keep saved allocations and allow explicit retry', async ({ page }, testInfo) => {
  await setup(page, [task('failure', '2026-09-07T12:00', 90)], [session('first')])
  const before = await raw(page)
  await sessionRows(page).getByRole('button', { name: /Rediger studieøkt/ }).click()
  await page.locator('#session-endTime').fill('11:30')
  await page.evaluate(() => { window.failWrite = true })
  await sessionSave(page).click()
  await expect(page.locator('#session-form')).toBeVisible()
  await expect(page.locator('#session-endTime')).toHaveValue('11:30')
  await expect(sessionSave(page)).toBeFocused()
  await expect(page.locator('#feedback')).toContainText('ikke lagret')
  await expect(planned(page, 'failure')).toContainText('Ikke planlagt: 30 min')
  expect(await raw(page)).toBe(before)
  await page.evaluate(() => { window.failWrite = false })
  await sessionSave(page).click()
  await expect(planned(page, 'failure')).toContainText('Ikke planlagt: 0 min')
  const afterSave = await raw(page)
  await page.evaluate(() => { window.failWrite = true })
  page.once('dialog', dialog => dialog.accept())
  await sessionRows(page).getByRole('button', { name: /Slett studieøkt/ }).click()
  expect(await raw(page)).toBe(afterSave)
  await expect(sessionRows(page)).toHaveCount(1)
  await expect(sessionRows(page).getByRole('button', { name: /Slett studieøkt/ })).toBeFocused()
  await page.evaluate(() => { window.failWrite = false })
  page.once('dialog', dialog => dialog.accept())
  await sessionRows(page).getByRole('button', { name: /Slett studieøkt/ }).click()
  await expect(sessionRows(page)).toHaveCount(0)
  await expect(planned(page, 'failure')).toContainText('Ikke planlagt: 90 min')
})

test('remaining edits change capacity and quick suggestions, zero stays open and existing actions preserve sessions', async ({ page }, testInfo) => {
  const work = task('remaining', '2026-09-07T12:00', 90)
  const sessions = [session('first')]
  await setup(page, [work], sessions)
  await planned(page, work.id).getByRole('button', { name: /Oppdater arbeid/ }).click()
  await expect(page.locator('#remainingMinutes')).toHaveValue('90')
  await page.locator('#remainingMinutes').fill('20')
  await page.evaluate(() => { window.failWrite = true })
  await save(page).click()
  await expect(page.locator('#remainingMinutes')).toHaveValue('20')
  await expect(planned(page, work.id)).toContainText('Gjenstående: 90 min')
  await page.evaluate(() => { window.failWrite = false })
  await save(page).click()
  await expect(planned(page, work.id)).toContainText('Gjenstående: 20 min')
  await navigate(page, 'time')
  await expect(page.locator('#task-list')).toContainText(work.title)
  await navigate(page, 'all')
  await openMenu(page, work.title)
  await checkbox(page, work.title).check()
  expect((await saved(page)).sessions).toEqual(sessions)
  await checkbox(page, work.title).uncheck()
  expect((await saved(page)).tasks[0]).toMatchObject({ completed: false, remainingMinutes: null })
  await openMenu(page, work.title)
  await edit(page, work.title).click()
  await page.locator('#remainingMinutes').fill('0')
  await save(page).click()
  await expect(checkbox(page, work.title)).not.toBeChecked()
  await navigate(page, 'capacity')
  await expect(planned(page, work.id)).toContainText('Gjenstående: 0 min')
  await expect(planned(page, work.id)).toContainText('Bekreft om oppgaven er fullført.')
  await expect(planned(page, work.id)).toContainText('Ikke fullført')
  expect((await saved(page)).tasks).toEqual([{ ...work, remainingMinutes: 0 }])
  expect((await saved(page)).sessions).toEqual(sessions)
})

test('failed session deletion at the bottom of a long mobile list keeps explanation and retry control visible', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 360, height: 900 })
  const sessions = Array.from({ length: 15 }, (_, index) => session(`study-${index}`, '10:00', '11:00', `2026-09-${String(index + 8).padStart(2, '0')}`))
  await setup(page, [task('long-list', '2026-09-30T12:00', 90)], sessions)
  const before = await raw(page)
  const last = sessionRows(page).last()
  const remove = last.getByRole('button', { name: /Slett studieøkt/ })
  await page.evaluate(() => { window.failWrite = true })
  await remove.focus()
  page.once('dialog', dialog => dialog.accept())
  await page.keyboard.press('Enter')
  await expectFocusFits(page, remove)
  await expect(last.getByRole('status')).toContainText('ikke slettet')
  expect(await last.getByRole('status').evaluate(node => { const bounds = node.getBoundingClientRect(); return bounds.top >= 0 && bounds.bottom <= innerHeight })).toBe(true)
  await page.clock.runFor(2000)
  await expect(last.getByRole('status')).toContainText('ikke slettet')
  expect(await raw(page)).toBe(before)
  await page.evaluate(() => { window.failWrite = false })
  page.once('dialog', dialog => dialog.accept())
  await page.keyboard.press('Enter')
  await expect(sessionRows(page)).toHaveCount(14)
})

test('ongoing sessions lose past minutes, midday deadlines clip time and overdue work does not consume future sessions', async ({ page }, testInfo) => {
  const tasks = [task('overdue', '2026-09-07T08:00', 30), task('midday', '2026-09-07T10:30', 90),
    { ...task('delivery', '2026-09-07T10:00', 45, true), requiresSubmission: true }]
  await setup(page, tasks, [session('ongoing', '08:00', '11:00')])
  await expect(planned(page, 'overdue')).toContainText('Satt av: 0 min · Ikke planlagt: 30 min')
  await expect(planned(page, 'midday')).toContainText('Satt av: 90 min · Ikke planlagt: 0 min')
  await expect(planned(page, 'midday')).toContainText('09:00–10:30: 90 min')
  await expect(planned(page, 'delivery')).toContainText('Klar til levering')
  await expect(planned(page, 'delivery')).toContainText('Gjenstående: 0 min')
  await expect(page.locator('#capacity-warnings')).toContainText('60')
  await page.clock.runFor(1000)
  await expect(planned(page, 'midday')).toContainText('Satt av: 89 min · Ikke planlagt: 1 min')
  expect(await writes(page)).toEqual([])
})

test('invalid saved session data blocks mutation and retries without startup migration', async ({ page }, testInfo) => {
  await setup(page, [task('invalid', '2026-09-07T12:00', 90)], [session('invalid', '12:00', '11:00')])
  const before = await raw(page)
  await expect(page.locator('#read-error')).toBeVisible()
  await expect(page.locator('#new-task')).toBeDisabled()
  await page.locator('#retry-read').click()
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
})

test('readable overlapping sessions count union once and can be repaired through calendar on a day without deadlines', async ({ page }, testInfo) => {
  const work = task('overlap', '2026-09-09T12:00', 150)
  await setup(page, [work], [session('first', '10:00', '12:00', '2026-09-08'), session('second', '11:00', '13:00', '2026-09-08')])
  await expect(page.locator('#capacity-summary')).toContainText('30 min ledig')
  await expect(page.locator('#capacity-warnings')).toContainText('bare telt én gang')
  await navigate(page, 'overview')
  await page.locator('#calendar-host').getByRole('button', { name: 'Månedsvisning', exact: true }).click()
  await page.locator('[data-calendar-date="2026-09-08"]').click()
  await expect(page.locator('.calendar-day-list [data-calendar-task]')).toHaveCount(0)
  await expect(page.locator('.calendar-day-list [data-calendar-session]')).toHaveCount(2)
  await expect(page.locator('[data-calendar-date="2026-09-08"]')).toContainText('Ø 2')
  await page.locator('#calendar-host').getByRole('button', { name: 'Agenda', exact: true }).click()
  const calendarEdit = page.locator('#compact-agenda [data-agenda-key="session:second"]')
  await calendarEdit.click()
  await expect(page.locator('#session-startTime')).toHaveValue('11:00')
  await expectModal(page, 'session-form')
  await page.locator('#session-startTime').fill('12:00')
  await sessionSave(page).click()
  await expect(calendarEdit).toBeFocused()
  await expect(page.locator('#compact-agenda .kind-session')).toHaveCount(2)
  await navigate(page, 'capacity')
  await expect(page.locator('#capacity-warnings')).toBeHidden()
  expect((await saved(page)).tasks).toEqual([work])
  expect((await saved(page)).sessions[1].startTime).toBe('12:00')
})

for (const width of [360, 1280]) {
  test(`capacity session flow and calendar labels retain visible keyboard controls at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await setup(page, [task('keyboard', '2026-09-07T12:00', 90)])
    await page.locator('#new-session').focus()
    await page.keyboard.press('Enter')
    await expectFocusFits(page, page.locator('#session-dateLocal'))
    await page.locator('#session-dateLocal').fill('2026-09-07')
    await tabTo(page, page.locator('#session-startTime'))
    await page.keyboard.type('10:00')
    await page.keyboard.press('Tab')
    await expectFocusFits(page, page.locator('#session-endTime'))
    await page.keyboard.type('11:00')
    await page.clock.runFor(2000)
    await expectFocusFits(page, page.locator('#session-endTime'))
    await tabTo(page, page.locator('#session-endDateLocal'))
    await tabTo(page, page.locator('#session-taskId'))
    await tabTo(page, sessionSave(page))
    await expectFocusFits(page, sessionSave(page))
    await page.screenshot({ path: testInfo.outputPath(`capacity-form-${width}.png`), fullPage: true })
    await page.keyboard.press('Enter')
    await expectFocusFits(page, page.locator('#new-session'))
    await tabTo(page, sessionRows(page).getByRole('button', { name: /Rediger studieøkt/ }))
    await page.clock.runFor(2000)
    await expectFocusFits(page, sessionRows(page).getByRole('button', { name: /Rediger studieøkt/ }))
    await page.screenshot({ path: testInfo.outputPath(`capacity-view-${width}.png`), fullPage: true })
    await navigate(page, 'overview')
    await expect(page.locator('#compact-agenda .kind-session')).toContainText('Studieøkt')
    await expect(page.locator('#compact-agenda .kind-deadline')).toContainText('Frist')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}
