import { navigate } from './helpers.js'
import { studyData } from './helpers.js'
import { openMenu, openRowMenu } from './helpers.js'
import { test, expect } from '@playwright/test'
import { task, seed, rows, row, checkbox, edit, save, saved, raw, writes, ids, expectFocusFits, instrumentWrites } from './helpers.js'

function expectStatusChangesAfterWrite(attempt, previousTask) {
  const previousStatus = `${previousTask.completed ? 'Fullført' : 'Ikke fullført'}`
  const nextStatus = `${previousTask.completed ? 'Ikke fullført' : 'Fullført'}`
  const successMessage = previousTask.completed ? 'Oppgaven er åpen igjen' : 'Oppgave fullført'
  const previousRow = attempt.rows.find(item => item.id === previousTask.id)
  expect(previousRow.status).toBe(previousStatus)
  expect(previousRow.status).not.toBe(nextStatus)
  expect(attempt.feedback).not.toContain(successMessage)
  expect(JSON.parse(attempt.previous).tasks.find(item => item.id === previousTask.id)).toEqual(previousTask)
  expect(JSON.parse(attempt.value).tasks.find(item => item.id === previousTask.id)).toEqual({ ...previousTask, completed: !previousTask.completed, ...(!previousTask.completed ? { remainingMinutes: 0 } : previousTask.remainingMinutes === 0 ? { remainingMinutes: null } : {}) })
}

test('completion records zero remaining work, reopening makes it unknown, and tied order survives reload and reopen', async ({ page, context }, testInfo) => {
  const tasks = [task('first'), task('selected"][data-extra="x'), task('last')]
  const selected = tasks[1]
  await seed(page, tasks, { view: 'all' })
  const before = await raw(page)
  await openMenu(page, selected.title)
  await checkbox(page, selected.title).focus()
  await page.keyboard.press('Space')
  await expectFocusFits(page, checkbox(page, selected.title))
  await expect(checkbox(page, selected.title)).toBeChecked()
  await expect(row(page, selected.title)).toContainText('Fullført')
  await expect(rows(page)).toHaveCount(3)
  const complete = tasks.map(item => item.id === selected.id ? { ...item, completed: true, remainingMinutes: 0 } : item)
  const { workLogs, ...completedData } = await studyData(page)
  expect(completedData).toEqual({ schemaVersion: 1, tasks: complete })
  expect(workLogs).toEqual([expect.objectContaining({ taskId: selected.id, outcome: 'done', actualMinutes: null, remainingMinutes: 0, taskSnapshot: selected })])
  expect(await ids(page)).toEqual(tasks.map(item => item.id))
  const attempts = await writes(page)
  expect(attempts).toHaveLength(1)
  expect(attempts[0].previous).toBe(before)
  expect(JSON.parse(attempts[0].value).tasks).toEqual(complete)
  expectStatusChangesAfterWrite(attempts[0], selected)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await page.locator('#course').fill('MAT100')
  await save(page).click()
  complete[1] = { ...complete[1], course: 'MAT100' }
  expect((await saved(page)).tasks).toEqual(complete)
  await page.reload()
  await navigate(page, 'all')
  await expect(checkbox(page, selected.title)).toBeChecked()
  expect(await ids(page)).toEqual(tasks.map(item => item.id))
  expect(await writes(page)).toEqual([])
  await page.close()
  const reopened = await context.newPage()
  await instrumentWrites(reopened)
  await reopened.goto('/')
  await navigate(reopened, 'all')
  expect((await saved(reopened)).tasks).toEqual(complete)
  await expect(checkbox(reopened, selected.title)).toBeChecked()
  await openMenu(reopened, selected.title)
  await checkbox(reopened, selected.title).focus()
  await reopened.keyboard.press('Space')
  await expectFocusFits(reopened, checkbox(reopened, selected.title))
  await expect(checkbox(reopened, selected.title)).not.toBeChecked()
  await expect(row(reopened, selected.title)).toContainText('Ikke fullført')
  const undoAttempts = await writes(reopened)
  expect(undoAttempts).toHaveLength(1)
  expectStatusChangesAfterWrite(undoAttempts[0], complete[1])
  complete[1] = { ...complete[1], completed: false, remainingMinutes: null }
  expect((await saved(reopened)).tasks).toEqual(complete)
  await reopened.reload()
  await navigate(reopened, 'all')
  await expect(checkbox(reopened, selected.title)).not.toBeChecked()
  expect(await ids(reopened)).toEqual(tasks.map(item => item.id))
  await reopened.close()
  const openedAgain = await context.newPage()
  await openedAgain.goto('/')
  await navigate(openedAgain, 'all')
  await expect(checkbox(openedAgain, selected.title)).not.toBeChecked()
  expect((await saved(openedAgain)).tasks).toEqual(complete)
})

for (const completed of [false, true]) {
  test(`failed ${completed ? 'undo' : 'completion'} restores visible and saved status and a keyboard retry succeeds`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 360, height: 900 })
    const tasks = Array.from({ length: 14 }, (_, i) => task(`failure-${i}`, '2026-09-01T12:00', 30, completed))
    const selected = tasks.at(-1)
    await seed(page, tasks, { view: 'all' })
    const before = await raw(page)
    await page.evaluate(() => { window.failWrite = true })
    const control = checkbox(page, selected.title)
    await openMenu(page, selected.title)
    await control.scrollIntoViewIfNeeded()
    await control.focus()
    await page.keyboard.press('Space')
    await expect(control).toBeChecked({ checked: completed })
    await expectFocusFits(page, control)
    await expect(control).toBeInViewport({ ratio: 1 })
    await expect(row(page, selected.title)).toContainText(/ikke lagret/i)
    const visibleError = row(page, selected.title).getByText(/ikke lagret/i)
    await expect(visibleError).toBeInViewport({ ratio: 1 })
    expect(await raw(page)).toBe(before)
    const failedAttempts = await writes(page)
    expect(failedAttempts).toHaveLength(1)
    expectStatusChangesAfterWrite(failedAttempts[0], selected)
    await page.clock.runFor(2000)
    await expect(control).toBeChecked({ checked: completed })
    await expect(control).toBeFocused()
    await expect(visibleError).toBeVisible()
    expect(await writes(page)).toHaveLength(1)
    await page.screenshot({ path: `test-results/${completed ? 'undo' : 'completion'}-write-failure.png` })
    await page.evaluate(() => { window.failWrite = false })
    await page.keyboard.press('Space')
    await expect(control).toBeChecked({ checked: !completed })
    await expect(control).toBeFocused()
    expect((await saved(page)).tasks).toEqual(tasks.map(item => item.id === selected.id ? { ...item, completed: !completed, ...(!completed ? { remainingMinutes: 0 } : {}) } : item))
    const retryAttempts = await writes(page)
    expect(retryAttempts).toHaveLength(2)
    expectStatusChangesAfterWrite(retryAttempts[1], selected)
    await expect(row(page, selected.title).getByText(/ikke lagret/i)).toHaveCount(0)
  })
}

test('same-title completion targets the selected ID and draft locks block synthetic status changes', async ({ page }, testInfo) => {
  const tasks = [task('one'), { ...task('two" ]'), title: 'Oppgave one' }]
  await seed(page, tasks, { view: 'all' })
  await openRowMenu(rows(page).nth(1))
  await rows(page).nth(1).getByRole('checkbox').check()
  expect((await saved(page)).tasks).toEqual([tasks[0], { ...tasks[1], completed: true, remainingMinutes: 0 }])
  expect(await writes(page)).toHaveLength(1)
  await openRowMenu(rows(page).nth(0))
  await rows(page).nth(0).getByRole('button', { name: /^Rediger / }).click()
  await page.locator('#title').fill('Ulagret utkast')
  for (const control of await rows(page).locator('button, input[type=checkbox]').all()) await expect(control).toBeDisabled()
  // A dispatched change event still cannot bypass the controller's draft guard.
  await rows(page).nth(1).getByRole('checkbox', { includeHidden: true }).dispatchEvent('change')
  await expect(page.locator('#title')).toHaveValue('Ulagret utkast')
  expect((await saved(page)).tasks).toEqual([tasks[0], { ...tasks[1], completed: true, remainingMinutes: 0 }])
  expect(await writes(page)).toHaveLength(1)
  await page.locator('#cancel-task').click()
  for (const control of await rows(page).locator('button:visible, input[type=checkbox]:visible').all()) await expect(control).toBeEnabled()
})
