import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { freeze, navigate, openTaskDetails, tabTo, key } from './helpers.js'

const stored = page => page.evaluate(key => JSON.parse(localStorage.getItem(key)), key)
const task = (id, patch = {}) => ({ id, title: `Oppgave ${id}`, course: '', deadlineLocal: '', remainingMinutes: null, estimatedMinutes: null, completed: false, ...patch })
async function seed(page, state) {
  await freeze(page, '2026-09-09T09:00:00+02:00'); await page.goto('/')
  await page.evaluate(({ key, state }) => localStorage.setItem(key, JSON.stringify(state)), { key, state }); await page.reload()
}
async function screenshot(page, info, name) {
  await page.clock.runFor(400)
  await page.screenshot({ path: info.outputPath(`${name}.png`) })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
}

test('independent A02: manual first course to title-only task and an edited free study session', async ({ page }, info) => {
  await freeze(page, '2026-09-09T09:00:00+02:00'); await page.goto('/')
  await page.locator('#connected-onboarding').getByRole('button', { name: 'Legg til manuelt', exact: true }).click()
  const editor = page.locator('#subject-editor')
  await editor.getByLabel('Emnenavn', { exact: true }).fill('Innføring i programmering')
  await editor.getByLabel('Emnekode', { exact: true }).fill('INF101')
  await editor.getByRole('button', { name: 'Lagre emne', exact: true }).click()
  const course = (await stored(page)).planner.courses[0]
  await navigate(page, 'overview')
  await page.locator('#connected-onboarding').getByRole('button', { name: 'Legg til første oppgave', exact: true }).click()
  await page.locator('#title').fill('Les første kapittel')
  expect(await page.locator('#task-form [name=courseId]').inputValue()).toBe(course.id)
  await page.locator('#task-form').getByRole('button', { name: 'Lagre', exact: true }).click()
  await navigate(page, 'capacity')
  const form = page.locator('.work-window-form')
  await form.locator('[name=startLocal]').fill('2026-09-09T10:00')
  await form.locator('[name=endLocal]').fill('2026-09-09T12:00')
  await form.getByRole('button', { name: 'Lagre tidsrom', exact: true }).click()
  await form.locator('[name=kind]').selectOption('busy')
  await form.locator('[name=startLocal]').fill('2026-09-09T10:00')
  await form.locator('[name=endLocal]').fill('2026-09-09T10:45')
  await form.getByRole('button', { name: 'Lagre tidsrom', exact: true }).click()
  await navigate(page, 'overview')
  await page.locator('#connected-onboarding').getByRole('button', { name: 'Velg foreslått økt', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Finn tid til første studieøkt', exact: true })
  await dialog.getByRole('checkbox', { name: 'Velg en utforskende økt: Les første kapittel', exact: true }).check()
  await dialog.getByRole('button', { name: 'Beregn nytt forslag', exact: true }).click()
  expect(await dialog.getByLabel('Ny start', { exact: true }).inputValue()).toBe('10:45')
  await dialog.getByLabel('Ny start', { exact: true }).fill('11:00')
  await dialog.getByLabel('Ny slutt', { exact: true }).fill('11:30')
  const before = await stored(page); expect(before.sessions || []).toHaveLength(0)
  await screenshot(page, info, 'onboarding-confirm-session-desktop')
  await dialog.getByRole('button', { name: 'Godta hele planen', exact: true }).click()
  const result = await stored(page)
  expect(result.tasks[0]).toMatchObject({ courseId: course.id, remainingMinutes: null })
  expect(result.sessions[0]).toMatchObject({ taskId: result.tasks[0].id, dateLocal: '2026-09-09', startTime: '11:00', endTime: '11:30' })
  await navigate(page, 'overview'); await page.locator('#connected-onboarding').getByRole('button', { name: 'Fullfør oppstart', exact: true }).click()
  await page.reload(); await expect(page.locator('#connected-onboarding')).toBeHidden()
  await page.setViewportSize({ width: 390, height: 844 }); await screenshot(page, info, 'first-plan-mobile')
})

test('independent A13/A14: actual backup download and restore preserve work, dependencies and disabled personalization', async ({ page }, info) => {
  const done = task('done', { title: 'Ferdig lesing', completed: true, remainingMinutes: 0, taskType: 'Lesing' })
  const pending = task('pending', { title: 'Skriv notater', dependencyIds: ['done'], remainingMinutes: 45 })
  const log = { id: 'work-public-test', operationId: 'public-test', taskId: done.id, at: '2026-09-08T12:00:00Z', outcome: 'done', actualMinutes: 30, plannedMinutes: null, remainingMinutes: 0, interrupted: false, historyComplete: true, taskSnapshot: { ...done, completed: false, remainingMinutes: 30 } }
  const state = { schemaVersion: 1, tasks: [done, pending], workLogs: [log], personalization: { enabled: false }, sessions: [{ id: 'future', taskId: pending.id, dateLocal: '2026-09-10', startTime: '12:00', endTime: '12:30' }] }
  await seed(page, state); await navigate(page, 'settings')
  const menu = page.locator('#settings-panel .data-menu'); if (!await menu.evaluate(element => element.open)) await menu.locator(':scope > summary').click()
  const downloadPromise = page.waitForEvent('download')
  await menu.getByRole('button', { name: 'Eksporter sikkerhetskopi', exact: true }).click()
  const download = await downloadPromise, file = await readFile(await download.path())
  expect(file.toString()).toContain('work-public-test')
  await page.evaluate(key => localStorage.removeItem(key), key); await page.reload(); await navigate(page, 'settings')
  await page.locator('#backup-file').setInputFiles({ name: 'isolert-sikkerhetskopi.json', mimeType: 'application/json', buffer: file })
  const dialog = page.getByRole('dialog', { name: 'Forhåndsvis gjenoppretting', exact: true })
  await expect(dialog).toBeVisible(); await screenshot(page, info, 'backup-confirmation-desktop')
  await dialog.getByRole('button', { name: 'Erstatt lokale data', exact: true }).click()
  const after = await stored(page)
  expect(after.tasks).toEqual(state.tasks); expect(after.sessions).toEqual(state.sessions); expect(after.workLogs).toEqual(state.workLogs); expect(after.personalization).toEqual({ enabled: false })
  await page.reload(); await navigate(page, 'settings')
  await expect(page.getByRole('checkbox', { name: 'Bruk lokal historikk til frivillige estimatforslag', exact: false })).not.toBeChecked()
})

test('independent A04/A13: larger text, keyboard capture and honest sparse-history state', async ({ page }, info) => {
  await freeze(page, '2026-09-09T09:00:00+02:00')
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/')
  await page.addStyleTag({ content: 'html { font-size: 200% !important; }' })
  const start = page.locator('#connected-onboarding').getByRole('button', { name: 'Legg til første oppgave', exact: true })
  await tabTo(page, start); await page.keyboard.press('Enter')
  await page.locator('#title').fill('En oppgave registrert med tastatur')
  await page.locator('.personal-estimate > summary').click()
  await expect(page.locator('.personal-estimate')).toContainText('Minst 5')
  await expect(page.locator('.personal-estimate button')).toBeHidden()
  await openTaskDetails(page)
  await page.locator('dialog[open]').evaluate(node => { node.scrollTop = 0 })
  await screenshot(page, info, 'quick-capture-large-text-mobile')
  await tabTo(page, page.locator('#task-form').getByRole('button', { name: 'Lagre', exact: true })); await page.keyboard.press('Enter')
  expect((await stored(page)).tasks[0].remainingMinutes).toBeNull()
})
