const localOrigin = `http://127.0.0.1:${process.env.PLAYWRIGHT_PORT || '5174'}`
import { expectModal } from './helpers.js'
import { navigate } from './helpers.js'
import { test, expect } from '@playwright/test'
import { task, seed, row, openMenu, edit, save, saved, raw, writes, fillDraft, fillDeadline, tabTo, expectFocusFits } from './helpers.js'

const calendar = page => page.locator('#calendar-panel')
const day = (page, date) => calendar(page).locator(`[data-calendar-date="${date}"]`)
const dayRows = page => calendar(page).locator('.calendar-day-list [data-calendar-task]')
const agendaRows = page => calendar(page).locator('#compact-agenda .kind-deadline')
const month = page => calendar(page).getByRole('button', { name: 'Månedsvisning', exact: true }).click()
const suggestions = page => page.locator('#dashboard-suggestions > li:visible')

for (const width of [360, 1280]) {
  for (const count of [0, 1, 12]) {
    test(`overview handles ${count} tasks at ${width}px with deadlines independent of suggestions and no writes`, async ({ page }, testInfo) => {
      await page.setViewportSize({ width, height: 900 })
      const source = Array.from({ length: count }, (_, index) => ({
        ...task(`overview-${index}`, index < 6 ? '2026-09-03T11:00' : '2026-09-04T16:00', 240),
        title: index === 0 ? 'Skriv rapport i IBE160' : `Oppgave ${index + 1}`,
        splittable: false,
        ...(index === 0 ? { remainingMinutes: 20, nextStep: { description: 'Les oppgaveteksten og lag en disposisjon', estimatedMinutes: 20 } } : {}),
      }))
      await seed(page, source, { view: 'overview' })
      const before = await raw(page)
      await expect(page.locator('#view-overview')).toHaveAttribute('aria-pressed', 'true')
      await expect(page.locator('#available-minutes')).toHaveValue('30')
      await expect(page.locator('#summary-week-count')).toHaveText(String(count))
      await expect(page.locator('#summary-overdue-count')).toHaveText(String(Math.min(6, count)))
      if (count === 0) {
        const onboarding = page.locator('#connected-onboarding')
        const firstTask = onboarding.getByRole('button', { name: 'Legg til første oppgave', exact: true })
        await expect(onboarding).toBeVisible()
        await expect(firstTask).toBeVisible()
        await expect(onboarding.getByRole('button', { name: 'Importer emne', exact: true })).toBeVisible()
        await expect(page.locator('#overview-summary')).toBeHidden()
        await expect(page.locator('#focus-panel')).toBeHidden()
        await expect(calendar(page)).toBeHidden()
        await expect(suggestions(page)).toHaveCount(0)
        await firstTask.click()
        await expectModal(page, 'task-form')
        await page.keyboard.press('Escape')
        await expect(firstTask).toBeFocused()
        const afterBeginning = await raw(page)
        expect((await saved(page)).tasks).toEqual([])
        await navigate(page, 'all')
        await expect(page.locator('#empty-tasks')).toBeVisible()
        await expect(calendar(page)).toBeVisible()
        await expect(calendar(page).locator('.agenda-empty')).toContainText('Luft i kalenderen')
        await navigate(page, 'overview')
        await expect(onboarding).toBeVisible()
        expect(await raw(page)).toBe(afterBeginning)
        expect(await writes(page)).toHaveLength(1)
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
        await page.screenshot({ path: testInfo.outputPath(`dashboard-${count}-tasks-${width}.png`), fullPage: true })
        return
      } else {
        await expect(calendar(page)).toBeVisible()
        await expect(suggestions(page)).toHaveCount(1)
        await expect(suggestions(page)).toContainText('Les oppgaveteksten og lag en disposisjon')
        await expect(suggestions(page)).toContainText('20 min · bare neste steg')
        await expect(row(page, source[0].title)).toBeVisible()
        if (count > 1) await expect(row(page, source[1].title)).toBeVisible()
        await page.getByRole('button', { name: '15 min', exact: true }).click()
        await expect(suggestions(page)).toHaveCount(0)
        await expect(page.locator('#suggestion-empty')).toBeVisible()
        await expect(row(page, source[0].title)).toBeVisible()
        await page.getByRole('button', { name: '30 min', exact: true }).click()
        await expect(suggestions(page)).toHaveCount(1)
      }
      for (const minutes of ['45', '60']) {
        const quickChoice = page.getByRole('button', { name: `${minutes} min`, exact: true })
        await quickChoice.click()
        await expect(quickChoice).toHaveAttribute('aria-pressed', 'true')
        await expect(page.locator('#available-minutes')).toHaveValue(minutes)
        await expect(suggestions(page)).toHaveCount(count === 0 ? 0 : 1)
      }
      await page.getByRole('button', { name: '30 min', exact: true }).click()
      if (count > 0) {
        const menu = row(page, source[0].title).locator('.task-menu')
        await tabTo(page, menu.locator('summary'))
        if (!await menu.evaluate(element => element.open)) await page.keyboard.press('Enter')
        await expect(menu).toHaveAttribute('open', '')
        await page.keyboard.press('Escape')
        await expect(menu).not.toHaveAttribute('open')
        await expectFocusFits(page, menu.locator('summary'))
      }
      await expect(calendar(page).getByRole('button', { name: 'Agenda', exact: true })).toHaveAttribute('aria-pressed', 'true')
      await expect(calendar(page).locator('.calendar-month-view')).toBeHidden()
      const upcoming = Math.max(0, count - 6)
      await expect(agendaRows(page)).toHaveCount(Math.min(5, upcoming))
      if (upcoming > 5) {
        await calendar(page).getByRole('button', { name: `Vis alle ${upcoming} hendelser`, exact: true }).click()
        await expect(agendaRows(page)).toHaveCount(upcoming)
        for (const item of source.slice(6)) await expect(agendaRows(page).filter({ hasText: item.title })).toBeVisible()
      }
      await month(page)
      await expect(calendar(page).locator('[data-calendar-date]')).toHaveCount(42)
      await expect(dayRows(page)).toHaveCount(Math.min(6, count))
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      expect(await raw(page)).toBe(before)
      expect(await writes(page)).toEqual([])
      await page.screenshot({ path: testInfo.outputPath(`dashboard-${count}-tasks-${width}.png`), fullPage: true })
      await tabTo(page, page.locator('#summary-week'))
      await page.keyboard.press('Enter')
      await expect(page.locator('#view-week')).toHaveAttribute('aria-pressed', 'true')
      await expectFocusFits(page, page.locator(width === 360 ? '#mobile-navigation-more' : '#view-week'))
      expect(await writes(page)).toEqual([])
    })
  }
}

test('calendar selects empty, single and multiple deadline days including separate completion and delivery states', async ({ page }, testInfo) => {
  const open = { ...task('open', '2026-09-03T11:00', 240), course: 'IBE160' }
  const ready = { ...task('ready', '2026-09-03T12:00', 20, true), requiresSubmission: true, course: 'MAT100' }
  const delivered = { ...task('delivered', '2026-09-03T09:00', 20, true), requiresSubmission: true, submitted: true }
  const complete = task('complete', '2026-09-03T10:00', 30, true)
  const single = task('single', '2026-09-05T20:30', 90)
  await seed(page, [open, ready, delivered, complete, single], { view: 'overview' })
  await month(page)
  await expect(calendar(page).locator('.calendar-weekdays')).toHaveText('ManTirOnsTorFreLørSøn')
  await expect(day(page, '2026-09-03')).toHaveAttribute('aria-current', 'date')
  await expect(day(page, '2026-09-03')).toHaveAttribute('aria-label', /4 oppgaver/)
  expect(await dayRows(page).evaluateAll(items => items.map(item => item.dataset.calendarTask))).toEqual([delivered.id, complete.id, open.id, ready.id])
  await expect(dayRows(page).filter({ hasText: ready.title })).toContainText('Klar til levering')
  await expect(dayRows(page).filter({ hasText: delivered.title })).toContainText('Levert (bekreftet manuelt)')
  await expect(dayRows(page).filter({ hasText: complete.title })).toContainText('Fullført')
  await expect(dayRows(page).filter({ hasText: delivered.title }).getByText('Forfalt', { exact: true })).toBeHidden()
  await expect(dayRows(page).filter({ hasText: open.title }).getByText('Forfalt', { exact: true })).toBeVisible()
  await expect(page.locator('#summary-ready-count')).toHaveText('1')
  await day(page, '2026-09-04').click()
  await expect(dayRows(page)).toHaveCount(0)
  await expect(calendar(page).getByText('Ingen frister denne dagen.', { exact: true })).toBeVisible()
  await day(page, '2026-09-05').click()
  await expect(dayRows(page)).toHaveCount(1)
  await expect(dayRows(page)).toContainText('kl. 20:30')
  await expect(dayRows(page)).toContainText(single.title)
  await calendar(page).getByRole('button', { name: 'I dag', exact: true }).click()
  await expect(dayRows(page)).toHaveCount(4)
  await expect(day(page, '2026-09-03')).toHaveAttribute('aria-pressed', 'true')
  expect(await writes(page)).toEqual([])
})

test('month navigation, keyboard date movement and midnight refresh preserve the selected day without storage writes', async ({ page }, testInfo) => {
  const december = task('december', '2026-12-31T23:59', 240)
  const january = task('january', '2027-01-01T00:00', 240)
  await seed(page, [december, january], { view: 'overview', now: '2026-12-31T23:59:59+01:00' })
  await month(page)
  await expect(row(page, january.title).locator('time')).toHaveText('1. januar 2027 kl. 00:00')
  await expect(row(page, december.title).locator('time')).toHaveText('31. desember kl. 23:59')
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('Desember 2026')
  await day(page, '2026-12-31').focus()
  await page.keyboard.press('ArrowRight')
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('Januar 2027')
  await expectFocusFits(page, day(page, '2027-01-01'))
  await expect(dayRows(page)).toContainText(january.title)
  await page.keyboard.press('ArrowLeft')
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('Desember 2026')
  await expectFocusFits(page, day(page, '2026-12-31'))
  await page.clock.runFor(2000)
  await expect(row(page, december.title).locator('time')).toHaveText('31. desember 2026 kl. 23:59')
  await expect(row(page, january.title).locator('time')).toHaveText('1. januar kl. 00:00')
  await expect(day(page, '2026-12-31')).toHaveAttribute('aria-pressed', 'true')
  await expect(day(page, '2027-01-01')).toHaveAttribute('aria-current', 'date')
  await expectFocusFits(page, day(page, '2026-12-31'))
  await expect(dayRows(page)).toContainText(december.title)
  await calendar(page).getByRole('button', { name: 'Neste måned', exact: true }).click()
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('Januar 2027')
  await calendar(page).getByRole('button', { name: 'Forrige måned', exact: true }).click()
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('Desember 2026')
  await calendar(page).getByRole('button', { name: 'I dag', exact: true }).click()
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('Januar 2027')
  await expect(day(page, '2027-01-01')).toHaveAttribute('aria-pressed', 'true')
  await expect(dayRows(page).getByText('Forfalt', { exact: true })).toBeVisible()
  expect((await saved(page)).tasks).toEqual([december, january])
  expect(await writes(page)).toEqual([])
})

test('editing from calendar, suggestion and task list updates one shared task and its deadline everywhere', async ({ page }, testInfo) => {
  const selected = { ...task('shared', '2026-09-03T20:30', 240), remainingMinutes: 20,
    nextStep: { description: 'Les oppgaveteksten', estimatedMinutes: 20 } }
  await seed(page, [selected], { view: 'overview' })
  await month(page)
  await dayRows(page).getByRole('button', { name: `Rediger «${selected.title}»`, exact: true }).click()
  await expect(page.locator('#title')).toBeFocused()
  await expect(page.locator('#deadlineDate')).toHaveValue('2026-09-03')
  await expect(page.locator('#deadlineTime')).toHaveValue('20:30')
  await fillDraft(page, { title: 'Rapporten er oppdatert', course: 'IBE160 nytt emne', deadlineLocal: '2026-09-10T18:45' })
  await save(page).click()
  await expect(dayRows(page)).toHaveCount(0)
  await day(page, '2026-09-10').click()
  await expect(dayRows(page)).toContainText('Rapporten er oppdatert')
  await expect(dayRows(page)).toContainText('kl. 18:45')
  await expect(suggestions(page)).toContainText('Rapporten er oppdatert')
  await suggestions(page).getByRole('button', { name: 'Åpne oppgave «Rapporten er oppdatert»', exact: true }).click()
  await expect(page.locator('#title')).toHaveValue('Rapporten er oppdatert')
  await page.locator('#cancel-task').click()
  await suggestions(page).locator('.task-menu > summary').click()
  await suggestions(page).getByRole('button', { name: 'Rediger neste steg «Rapporten er oppdatert»', exact: true }).click()
  await expect(page.locator('#step-description')).toHaveValue('Les oppgaveteksten')
  await page.locator('#step-description').fill('Lag en kort disposisjon')
  await page.locator('#step-form').getByRole('button', { name: 'Lagre neste steg', exact: true }).click()
  await expect(suggestions(page)).toContainText('Lag en kort disposisjon')
  await navigate(page, 'all')
  await openMenu(page, 'Rapporten er oppdatert')
  await edit(page, 'Rapporten er oppdatert').click()
  await fillDeadline(page, '2026-09-04T21:15')
  await save(page).click()
  await expect(row(page, 'Rapporten er oppdatert').locator('time')).toHaveAttribute('datetime', '2026-09-04T21:15')
  await expect(dayRows(page)).toHaveCount(0)
  await day(page, '2026-09-04').click()
  await expect(dayRows(page)).toContainText('kl. 21:15')
  expect((await saved(page)).tasks).toEqual([{ ...selected, title: 'Rapporten er oppdatert', course: 'IBE160 nytt emne', deadlineLocal: '2026-09-04T21:15', nextStep: { description: 'Lag en kort disposisjon', estimatedMinutes: 20 } }])
  expect(await writes(page)).toHaveLength(3)
  await page.reload()
  await navigate(page, 'all')
  await month(page)
  await expect(row(page, 'Rapporten er oppdatert')).toContainText('Lag en kort disposisjon')
  await day(page, '2026-09-04').click()
  await expect(dayRows(page)).toContainText('kl. 21:15')
  expect(await writes(page)).toEqual([])
})

test('Norwegian 24-hour entry and deadline display stay unambiguous in an en-US browser', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ baseURL: localOrigin, locale: 'en-US', timezoneId: 'Europe/Oslo', viewport: { width: 1280, height: 900 } })
  const page = await context.newPage()
  try {
    await seed(page, [], { view: 'all' })
    await month(page)
    await page.locator('#new-task').click()
    await fillDraft(page, { title: 'Kveldens innlevering', course: 'IBE160', deadlineLocal: '2026-09-03T20:30', estimatedMinutes: '90' })
    await expect(page.locator('#deadlineTime')).toHaveAttribute('type', 'text')
    await expect(page.locator('#deadlineTime')).toHaveValue('20:30')
    await save(page).click()
    expect((await saved(page)).tasks[0].deadlineLocal).toBe('2026-09-03T20:30')
    await expect(row(page, 'Kveldens innlevering').locator('time')).toHaveText('3. september kl. 20:30')
    await expect(dayRows(page)).toContainText('kl. 20:30')
    await expect(page.locator('body')).not.toContainText(/\b(?:AM|PM)\b/)
    await dayRows(page).getByRole('button', { name: 'Rediger «Kveldens innlevering»', exact: true }).click()
    await expect(page.locator('#deadlineTime')).toHaveValue('20:30')
    await tabTo(page, page.locator('#cancel-task'))
    await page.keyboard.press('Enter')
    await page.screenshot({ path: testInfo.outputPath('24-hour-en-US.png'), fullPage: true })
  } finally { await context.close() }
})

test('mobile agenda and month controls remain usable through keyboard navigation, editing, clock and view changes', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 360, height: 900 })
  const first = task('mobile-first', '2026-09-03T20:30', 240)
  const later = task('mobile-later', '2026-09-10T16:00', 180)
  await seed(page, [first, later], { view: 'overview' })
  const before = await raw(page)
  await tabTo(page, calendar(page).getByRole('button', { name: 'Månedsvisning', exact: true }))
  await page.keyboard.press('Enter')
  await tabTo(page, day(page, '2026-09-03'))
  await page.keyboard.press('ArrowDown')
  await expectFocusFits(page, day(page, '2026-09-10'))
  await expect(dayRows(page)).toContainText(later.title)
  await page.keyboard.press('Home')
  await expectFocusFits(page, day(page, '2026-09-07'))
  await page.keyboard.press('End')
  await expectFocusFits(page, day(page, '2026-09-13'))
  await expect(dayRows(page)).toHaveCount(0)
  await tabTo(page, calendar(page).getByRole('button', { name: 'Agenda', exact: true }))
  await page.keyboard.press('Enter')
  await expect(agendaRows(page)).toHaveCount(2)
  await page.clock.runFor(2000)
  await navigate(page, 'all')
  await expect(calendar(page).getByRole('button', { name: 'Agenda', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const agendaEdit = calendar(page).locator(`[data-agenda-key="task:${first.id}"]`)
  await tabTo(page, agendaEdit)
  await page.keyboard.press('Enter')
  await expectFocusFits(page, page.locator('#title'))
  await expect(page.locator('#title')).toHaveValue(first.title)
  await expectModal(page, 'task-form')
  await page.clock.runFor(2000)
  await page.locator('#title').focus()
  for (const button of await agendaRows(page).locator('button').all()) {
    await button.focus()
    await expect(page.locator('#title')).toBeFocused()
  }
  await tabTo(page, page.locator('#cancel-task'))
  await page.keyboard.press('Enter')
  await expectFocusFits(page, agendaEdit)
  await month(page)
  await calendar(page).getByRole('button', { name: 'Neste måned', exact: true }).click()
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('Oktober 2026')
  await expect(calendar(page).locator('[data-calendar-date]')).toHaveCount(42)
  await calendar(page).getByRole('button', { name: 'Forrige måned', exact: true }).click()
  await expect(calendar(page).locator('.calendar-month-heading')).toHaveText('September 2026')
  await calendar(page).getByRole('button', { name: 'Agenda', exact: true }).click()
  await expect(agendaRows(page)).toHaveCount(2)
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mobile-agenda-navigation.png'), fullPage: true })
})
