import { navigate } from './helpers.js'
import { openMenu, openRowMenu, fillDraft, row, edit, remove, tabTo } from './helpers.js'
import { test, expect } from '@playwright/test'
import { expectFocusFits as expectVisibleFocusAndFit } from './helpers.js'

const key = 'studieplanlegger:v1'
const first = { id: 'first', title: 'Første oppgave', course: 'IBE160', deadlineLocal: '2026-09-20T12:00', estimatedMinutes: 60, completed: false }
const selected = { ...first, id: 'selected"][data-extra="x', title: 'Oppgaven som rettes', deadlineLocal: '2026-09-25T12:00', completed: true }
const last = { ...first, id: 'last', title: 'Siste oppgave', deadlineLocal: '2026-09-30T12:00' }
const fields = ['title', 'course', 'deadlineLocal', 'remainingMinutes']
const save = page => page.getByRole('button', { name: 'Lagre', exact: true })
const rawValue = page => page.evaluate(key => localStorage.getItem(key), key)
const attempts = page => page.evaluate(() => window.writeAttempts)

async function seed(page, tasks = [first, selected, last]) {
  // Seed only once, before instrumentation: reloading must read the actual saved result.
  await page.goto('/')
  await page.evaluate(({ key, tasks }) => localStorage.setItem(key, JSON.stringify({ schemaVersion: 1, tasks })), { key, tasks })
  await page.addInitScript(key => {
    window.writeAttempts = []
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (storageKey, value) {
      if (storageKey === key) {
        window.writeAttempts.push({ value, list: document.querySelector('#task-list').textContent, feedback: document.querySelector('#feedback').textContent })
        if (window.failWrite) throw Error('Injected write failure')
      }
      return original.call(this, storageKey, value)
    }
  }, key)
  await page.reload()
  await navigate(page, 'all')
  await expect(page.locator('#task-list li')).toHaveCount(tasks.length)
  expect(await attempts(page)).toEqual([])
}

async function expectDraft(page, task) {
  for (const field of fields) await expect(page.locator(`#${field}`)).toHaveValue(String(field === 'remainingMinutes' ? Object.hasOwn(task, field) ? task[field] ?? '' : task.estimatedMinutes ?? '' : task[field]))
}

async function confirmDelete(page, title, accept = true, keyboard = false) {
  if (!keyboard) await openMenu(page, title)
  const dialogPromise = page.waitForEvent('dialog')
  const actionPromise = keyboard ? page.keyboard.press('Enter') : remove(page, title).click()
  const dialog = await dialogPromise
  expect(dialog.type()).toBe('confirm')
  expect(dialog.message()).toContain(title)
  if (accept) await dialog.accept()
  else await dialog.dismiss()
  await actionPromise
}

test('all-field edit retains identity, completed status, storage order and tied display order across reload and reopen', async ({ page, context }, testInfo) => {
  await seed(page)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await expect(page.getByRole('heading', { name: 'Rediger oppgave', exact: true })).toBeVisible()
  await expectDraft(page, selected)
  const draft = { title: ' <img src=x onerror=alert(1)> ', course: ' MAT100 ', deadlineLocal: first.deadlineLocal, remainingMinutes: 95 }
  await fillDraft(page, draft)
  await save(page).click()
  const changed = { ...selected, ...draft, title: draft.title.trim(), course: draft.course.trim() }
  const expected = [first, changed, last]
  await expect(page.getByRole('status')).toHaveText('Endringer lagret')
  await expect(edit(page, changed.title)).toBeFocused()
  await expect(row(page, changed.title)).toContainText('Fullført')
  await expect(row(page, changed.title)).toContainText('MAT100')
  await expect(row(page, changed.title)).toContainText('Gjenstående arbeid: 0 min')
  await expect(row(page, changed.title)).toContainText('20. september kl. 12:00')
  await expect(page.locator('#task-list img')).toHaveCount(0)
  const { history, ...stored } = JSON.parse(await rawValue(page))
  expect(stored).toEqual({ schemaVersion: 1, tasks: expected })
  expect(history).toMatchObject({ version: 1, trash: [], undo: [{ changes: [{ path: 'tasks', id: selected.id, before: selected, after: changed }] }] })
  const writes = await attempts(page)
  expect(writes).toHaveLength(1)
  expect(writes[0].list).toContain(selected.title)
  expect(writes[0].list).not.toContain(changed.title)
  expect(writes[0].feedback).not.toContain('Endringer lagret')
  expect(JSON.parse(writes[0].value).tasks).toEqual(expected)
  expect(await page.locator('#task-list li').evaluateAll(items => items.map(item => item.dataset.taskId))).toEqual(expected.map(task => task.id))
  await page.reload()
  await navigate(page, 'all')
  expect(await attempts(page)).toEqual([])
  expect(JSON.parse(await rawValue(page)).tasks).toEqual(expected)
  expect(await page.locator('#task-list li').evaluateAll(items => items.map(item => item.dataset.taskId))).toEqual(expected.map(task => task.id))
  await expect(row(page, changed.title)).toContainText('Fullført')
  await confirmDelete(page, first.title)
  await expect(page.getByRole('status')).toHaveText('Oppgave slettet')
  expect(await attempts(page)).toHaveLength(1)
  await page.reload()
  await navigate(page, 'all')
  expect(await attempts(page)).toEqual([])
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([changed, last])
  await expect(row(page, first.title)).toHaveCount(0)
  await page.close()
  const reopened = await context.newPage()
  await reopened.goto('/')
  await navigate(reopened, 'all')
  expect(JSON.parse(await rawValue(reopened)).tasks).toEqual([changed, last])
  await expect(reopened.locator('#task-list li')).toHaveCount(2)
  await expect(row(reopened, first.title)).toHaveCount(0)
  await expect(row(reopened, changed.title)).toContainText('Fullført')
  await openMenu(reopened, changed.title)
  await edit(reopened, changed.title).click()
  await expectDraft(reopened, changed)
})

test('cancel discards changed edit draft and blocks other task actions without writes', async ({ page }, testInfo) => {
  await seed(page)
  const raw = await rawValue(page)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await fillDraft(page, { title: 'Ulagret endring', course: 'Et annet emne', deadlineLocal: '2026-10-25T02:30', remainingMinutes: 15 })
  for (const action of await page.locator('#task-list button, #task-list input[type=checkbox]').all()) await expect(action).toBeDisabled()
  await page.locator('#task-list button, #task-list input[type=checkbox]').evaluateAll(buttons => buttons.forEach(button => button.click()))
  await expect(page.locator('#title')).toHaveValue('Ulagret endring')
  await page.locator('#cancel-task').click()
  await expect(page.locator('#task-form')).not.toBeVisible()
  await expect(edit(page, selected.title)).toBeFocused()
  expect(await rawValue(page)).toBe(raw)
  expect(await attempts(page)).toEqual([])
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await expectDraft(page, selected)
  for (const field of fields) {
    await expect(page.locator(`#${field}-error`)).toHaveText('')
    await expect(page.locator(`#${field === 'deadlineLocal' ? 'deadlineTime' : field}`)).toHaveAttribute('aria-invalid', 'false')
  }
  await page.locator('#cancel-task').click()
  await page.locator('#new-task').click()
  for (const field of fields) await expect(page.locator(`#${field}`)).toHaveValue('')
  await expect(page.getByRole('heading', { name: 'Ny oppgave', exact: true })).toBeVisible()
  expect(await attempts(page)).toEqual([])
})

test('invalid edits retain saved tasks and draft, focus errors and never write', async ({ page }, testInfo) => {
  await seed(page)
  const raw = await rawValue(page)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  const invalid = { title: ' ', course: ' ', deadlineLocal: '2026-03-29T02:30', remainingMinutes: '9007199254740992' }
  await fillDraft(page, invalid)
  await save(page).click()
  await expectDraft(page, invalid)
  for (const field of fields.filter(field => field !== 'course')) {
    await expect(page.locator(`#${field === 'deadlineLocal' ? 'deadlineTime' : field}`)).toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator(`#${field === 'deadlineLocal' ? 'deadlineTime' : field}`)).toHaveAttribute('aria-describedby', field === 'remainingMinutes' ? 'remainingMinutes-help remainingMinutes-error' : `${field}-error`)
    await expect(page.locator(`#${field}-error`)).not.toHaveText('')
  }
  await expect(page.locator('#title')).toBeFocused()
  await fillDraft(page, { title: selected.title, course: selected.course, deadlineLocal: selected.deadlineLocal })
  for (const remainingMinutes of ['-1', '1.5', '2e2', '9007199254740992']) {
    await page.locator('#remainingMinutes').fill(remainingMinutes)
    await save(page).click()
    await expect(page.locator('#remainingMinutes')).toBeFocused()
    await expect(page.locator('#remainingMinutes')).toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator('#remainingMinutes')).toHaveValue(remainingMinutes)
  }
  await fillDraft(page, { remainingMinutes: 60, deadlineLocal: 'T12:00' })
  await save(page).click()
  await expect(page.locator('#deadlineDate')).toBeFocused()
  await expect(page.locator('#deadlineDate')).toHaveAttribute('aria-invalid', 'true')
  expect(await rawValue(page)).toBe(raw)
  expect(await attempts(page)).toEqual([])
  await expect(page.locator('#task-list li')).toHaveCount(3)
  await expect(row(page, selected.title)).toContainText('Hele oppgaven: 60 min')
  await page.locator('#cancel-task').click()
  await expect(edit(page, selected.title)).toBeFocused()
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await expectDraft(page, selected)
  for (const field of fields) await expect(page.locator(`#${field}-error`)).toHaveText('')
  expect(await attempts(page)).toEqual([])
})

test('delete confirmation can cancel, removes selected ID only, and focuses next, previous or new task', async ({ page }, testInfo) => {
  // Storage order deliberately differs from visible order.
  await seed(page, [last, first, selected])
  const raw = await rawValue(page)
  await confirmDelete(page, selected.title, false)
  expect(await rawValue(page)).toBe(raw)
  expect(await attempts(page)).toEqual([])
  await expect(page.locator('#task-list li')).toHaveCount(3)
  await confirmDelete(page, selected.title)
  await expect(page.getByRole('status')).toHaveText('Oppgave slettet')
  await expect(edit(page, last.title)).toBeFocused()
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([last, first])
  const writes = await attempts(page)
  expect(writes).toHaveLength(1)
  expect(writes[0].list).toContain(selected.title)
  expect(writes[0].feedback).not.toContain('Oppgave slettet')
  await expect(row(page, selected.title)).toHaveCount(0)
  await confirmDelete(page, last.title)
  await expect(edit(page, first.title)).toBeFocused()
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([first])
  await confirmDelete(page, first.title)
  await expect(page.locator('#new-task')).toBeFocused()
  await expect(page.locator('#empty-tasks')).toBeVisible()
  await expect(page.locator('#task-list li')).toHaveCount(0)
  const { history, ...stored } = JSON.parse(await rawValue(page))
  expect(stored).toEqual({ schemaVersion: 1, tasks: [] })
  expect(history.version).toBe(1)
  expect(history.undo).toHaveLength(3)
  expect(history.trash.map(entry => entry.changes.map(change => ({ id: change.id, before: change.before, after: change.after })))).toEqual(
    [selected, last, first].map(task => [{ id: task.id, before: task, after: null }]),
  )
  expect(await attempts(page)).toHaveLength(3)
})

test('failed edit preserves prior list, raw value and every draft field; retry updates once', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 360, height: 500 })
  await seed(page)
  const raw = await rawValue(page)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  const draft = { title: ' Endret oppgave ', course: ' MAT100 ', deadlineLocal: '2026-09-01T10:45', remainingMinutes: 25 }
  await fillDraft(page, draft)
  await page.evaluate(() => { window.failWrite = true })
  await save(page).click()
  await expect(page.getByRole('status')).toContainText('Endringen ble ikke lagret')
  await expect(page.getByRole('status')).toBeInViewport({ ratio: 1 })
  await expect(save(page)).toBeInViewport({ ratio: 1 })
  await expect(save(page)).toBeFocused()
  await expectDraft(page, draft)
  await expect(page.locator('#task-form')).toBeVisible()
  await expect(page.locator('#task-list li')).toHaveCount(3)
  await expect(row(page, selected.title)).toContainText('25. september kl. 12:00')
  await expect(row(page, selected.title)).toContainText('Hele oppgaven: 60 min')
  await expect(row(page, draft.title.trim())).toHaveCount(0)
  expect(await rawValue(page)).toBe(raw)
  expect(await attempts(page)).toHaveLength(1)
  await page.screenshot({ path: testInfo.outputPath('edit-write-failure.png') })
  await page.evaluate(() => { window.failWrite = false })
  await save(page).click()
  const changed = { ...selected, ...draft, title: draft.title.trim(), course: draft.course.trim() }
  await expect(page.getByRole('status')).toHaveText('Endringer lagret')
  await expect(edit(page, changed.title)).toBeFocused()
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([first, changed, last])
  expect(await attempts(page)).toHaveLength(2)
  await expect(page.locator('#task-list li')).toHaveCount(3)
  await expect(page.locator('#task-list li').first()).toHaveAttribute('data-task-id', selected.id)
})

test('failed deletion near the end of a long list shows the error in viewport, preserves data and supports retry', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 360, height: 900 })
  const preceding = Array.from({ length: 12 }, (_, index) => ({
    ...first, id: `preceding-${index}`, title: `Tidligere oppgave ${index + 1}`, deadlineLocal: '2026-09-21T12:00',
  }))
  const tasks = [first, ...preceding, selected, last]
  await seed(page, tasks)
  const raw = await rawValue(page)
  await openMenu(page, selected.title)
  await remove(page, selected.title).scrollIntoViewIfNeeded()
  await expect(page.locator('#new-task')).not.toBeInViewport()
  await page.evaluate(() => { window.failWrite = true })
  await confirmDelete(page, selected.title)
  const failure = page.getByText('Oppgaven ble ikke slettet. Lagrede oppgaver er beholdt. Prøv Slett igjen.', { exact: true })
  await expect(failure).toContainText('Oppgaven ble ikke slettet')
  await expect(failure).toBeInViewport({ ratio: 1 })
  await expect(page.locator('#task-list li')).toHaveCount(tasks.length)
  await expect(row(page, selected.title)).toBeVisible()
  await expect(remove(page, selected.title)).toBeEnabled()
  await expect(remove(page, selected.title)).toBeFocused()
  await expect(remove(page, selected.title)).toBeInViewport({ ratio: 1 })
  expect(await rawValue(page)).toBe(raw)
  expect(await attempts(page)).toHaveLength(1)
  await page.screenshot({ path: testInfo.outputPath('delete-write-failure.png') })
  await page.evaluate(() => { window.failWrite = false })
  await confirmDelete(page, selected.title)
  await expect(page.getByRole('status')).toHaveText('Oppgave slettet')
  await expect(edit(page, last.title)).toBeFocused()
  await expect(row(page, selected.title)).toHaveCount(0)
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([first, ...preceding, last])
  expect(await attempts(page)).toHaveLength(2)
})

test('same-title tasks dispatch edit and delete to the selected ID and have task-specific accessible names', async ({ page }, testInfo) => {
  const duplicateTitle = 'Lik oppgavetittel'
  const one = { ...first, title: duplicateTitle }
  const two = { ...selected, title: duplicateTitle, deadlineLocal: one.deadlineLocal }
  await seed(page, [one, two])
  const secondRow = page.locator('#task-list li').nth(1)
  await openRowMenu(secondRow)
  const secondEdit = secondRow.getByRole('button', { name: `Rediger «${duplicateTitle}»`, exact: true })
  const secondDelete = secondRow.getByRole('button', { name: `Slett «${duplicateTitle}»`, exact: true })
  await expect(secondEdit).toHaveText('Rediger')
  await expect(secondDelete).toHaveText('Slett')
  await secondEdit.click()
  await expectDraft(page, two)
  await fillDraft(page, { course: 'Endret emne', remainingMinutes: 95 })
  await save(page).click()
  const changed = { ...two, course: 'Endret emne', remainingMinutes: 95 }
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([one, changed])
  await expect(secondEdit).toBeFocused()
  await expect(secondRow).toHaveAttribute('data-task-id', two.id)
  await secondDelete.focus()
  await confirmDelete(page, duplicateTitle, true, true)
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([one])
  await expect(page.locator('#task-list li')).toHaveCount(1)
  await expect(page.locator('#task-list li')).toHaveAttribute('data-task-id', one.id)
  expect(await attempts(page)).toHaveLength(2)
})

test('creation draft locks existing task actions and cancel or save restores them without unintended writes', async ({ page }, testInfo) => {
  await seed(page)
  const prior = await rawValue(page)
  const draft = { title: 'Ny fiktiv oppgave', course: 'TEST', deadlineLocal: '2026-10-25T02:30', remainingMinutes: 30 }
  await page.locator('#new-task').click()
  await fillDraft(page, draft)
  for (const action of await page.locator('#task-list button, #task-list input[type=checkbox]').all()) await expect(action).toBeDisabled()
  await page.locator('#task-list button, #task-list input[type=checkbox]').evaluateAll(buttons => buttons.forEach(button => button.click()))
  await expectDraft(page, draft)
  expect(await rawValue(page)).toBe(prior)
  expect(await attempts(page)).toEqual([])
  await page.locator('#cancel-task').click()
  await expect(page.locator('#new-task')).toBeFocused()
  for (const action of await page.locator('#task-list button:visible, #task-list input[type=checkbox]:visible').all()) await expect(action).toBeEnabled()
  expect(await attempts(page)).toEqual([])
  await page.locator('#new-task').click()
  for (const field of fields) await expect(page.locator(`#${field}`)).toHaveValue('')
  await fillDraft(page, draft)
  await save(page).click()
  await expect(page.locator('#new-task')).toBeFocused()
  for (const action of await page.locator('#task-list button:visible, #task-list input[type=checkbox]:visible').all()) await expect(action).toBeEnabled()
  const saved = JSON.parse(await rawValue(page)).tasks
  expect(saved).toHaveLength(4)
  expect(saved.slice(0, 3)).toEqual([first, selected, last])
  expect(saved[3]).toMatchObject({ ...draft, completed: false })
  expect(new Set(saved.map(task => task.id)).size).toBe(4)
  expect(await attempts(page)).toHaveLength(1)
})

test('cancel after failed edit reopens saved values and a later save cannot persist the cancelled draft', async ({ page }, testInfo) => {
  await seed(page)
  const prior = await rawValue(page)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await fillDraft(page, { title: 'Skal aldri lagres', course: 'Ulagret emne', deadlineLocal: '2026-09-01T10:30', remainingMinutes: 15 })
  await page.evaluate(() => { window.failWrite = true })
  await save(page).click()
  await expect(page.getByRole('status')).toContainText('Endringen ble ikke lagret')
  await page.locator('#cancel-task').click()
  await expect(edit(page, selected.title)).toBeFocused()
  await expect(page.locator('#feedback')).toHaveText('')
  expect(await attempts(page)).toHaveLength(1)
  expect(await rawValue(page)).toBe(prior)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await expectDraft(page, selected)
  for (const field of fields) await expect(page.locator(`#${field}-error`)).toHaveText('')
  await page.locator('#cancel-task').click()
  expect(await attempts(page)).toHaveLength(1)
  await page.evaluate(() => { window.failWrite = false })
  await openMenu(page, first.title)
  await edit(page, first.title).click()
  await page.locator('#title').fill('En annen oppgave er rettet')
  await save(page).click()
  expect(JSON.parse(await rawValue(page)).tasks).toEqual([{ ...first, title: 'En annen oppgave er rettet' }, selected, last])
  expect(await attempts(page)).toHaveLength(2)
  await expect(row(page, 'Skal aldri lagres')).toHaveCount(0)
})

for (const width of [360, 1280]) {
  test(`edit, cancel and delete are reachable by keyboard with visible focus at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    const longTitle = 'Langoppgave'.repeat(20)
    const longTask = { ...first, title: longTitle, course: 'Langtemnenavn'.repeat(12) }
    await seed(page, [longTask, selected])
    await tabTo(page, row(page, longTitle).locator('.task-menu > summary'))
    await page.keyboard.press('Enter')
    await tabTo(page, edit(page, longTitle))
    await page.keyboard.press('Enter')
    await expectVisibleFocusAndFit(page, page.locator('#title'))
    const stops = ['#remainingMinutes', '#course', '#deadlineDate', '#deadlineTime', '#requiresSubmission', '#task-form button[type="submit"]', '#cancel-task']
    for (const stop of stops) await tabTo(page, page.locator(stop))
    await page.screenshot({ path: testInfo.outputPath(`edit-form-${width}.png`), fullPage: true })
    await page.keyboard.press('Enter')
    await expectVisibleFocusAndFit(page, edit(page, longTitle))
    expect(await attempts(page)).toEqual([])
    await page.keyboard.press('Enter')
    await page.keyboard.press('ControlOrMeta+A')
    await page.keyboard.press('Backspace')
    await page.keyboard.press('Enter')
    await expect(page.locator('#title')).toHaveAttribute('aria-invalid', 'true')
    await expectVisibleFocusAndFit(page, page.locator('#title'))
    await page.screenshot({ path: testInfo.outputPath(`edit-errors-${width}.png`), fullPage: true })
    await page.keyboard.type('Rettet med tastaturet')
    for (const stop of stops.slice(0, -1)) await tabTo(page, page.locator(stop))
    await page.keyboard.press('Enter')
    await expectVisibleFocusAndFit(page, edit(page, 'Rettet med tastaturet'))
    await page.screenshot({ path: testInfo.outputPath(`edited-task-${width}.png`), fullPage: true })
    await tabTo(page, remove(page, 'Rettet med tastaturet'))
    await confirmDelete(page, 'Rettet med tastaturet', false, true)
    await expectVisibleFocusAndFit(page, remove(page, 'Rettet med tastaturet'))
    expect(await attempts(page)).toHaveLength(1)
    await confirmDelete(page, 'Rettet med tastaturet', true, true)
    await expectVisibleFocusAndFit(page, edit(page, selected.title))
    await page.screenshot({ path: testInfo.outputPath(`deleted-task-${width}.png`), fullPage: true })
    await tabTo(page, remove(page, selected.title))
    await confirmDelete(page, selected.title, true, true)
    await expectVisibleFocusAndFit(page, page.locator('#new-task'))
    await expect(page.locator('#empty-tasks')).toBeVisible()
    expect(await attempts(page)).toHaveLength(3)
  })
}
