import { test, expect } from '@playwright/test'
import { navigate, saved, openCourseImport } from './helpers.js'

test('NMBU metadata version mismatch retains the verified hyphenated TimeEdit selection', async ({ page }) => {
  await page.route('**/api/import/providers/nmbu/search?**', route => route.fulfill({ json: { status: 'ok', results: [{ code: 'MATH-INF100', name: 'MATH-INF100,2026 HØST', label: 'MATH-INF100,2026 HØST', sourceObjectId: 'test.5', university: 'NMBU', year: 2026, semester: 'autumn', entryUrl: 'https://cloud.timeedit.net/nmbu/web/student/ri1Q7.html' }] } }))
  await page.route('**/api/import/providers/nmbu/details?**', route => route.fulfill({ json: { status: 'semester-unavailable', error: 'Annet studieår i emnekatalogen.' } }))
  await page.goto('/'); await navigate(page, 'subjects')
  await openCourseImport(page)
  await page.locator('#course-import-form [name=university]').selectOption('nmbu')
  await expect(page.locator('.import-wizard')).toContainText('Steg 1')
  await expect(page.locator('#course-import-form [name=code]')).toBeHidden()
  await page.getByRole('button', { name: 'Neste: søk og semester' }).click()
  await page.locator('#course-import-form [name=code]').fill('MATH-INF100')
  await page.locator('#course-import-form [name=year]').fill('2026')
  await page.locator('#ntnu-fetch').click()
  await expect(page.locator('#course-import-form')).toBeHidden()
  await page.locator('.wizard-results button').click()
  await expect(page.locator('#import-preview')).toContainText('TimeEdit-valget er beholdt')
  await page.getByRole('button', { name: 'Tilbake', exact: true }).click()
  await expect(page.locator('.wizard-results')).toContainText('MATH-INF100')
  await page.getByRole('button', { name: 'Tilbake', exact: true }).click()
  await expect(page.locator('#course-import-form [name=code]')).toBeVisible()
  await expect(page.locator('#course-import-form [name=code]')).toHaveValue('MATH-INF100')
  await page.getByRole('button', { name: 'Tilbake', exact: true }).click()
  await expect(page.locator('#course-import-form [name=university]')).toHaveValue('nmbu')
  await page.getByRole('button', { name: 'Neste: søk og semester' }).click()
  await expect(page.locator('#course-import-form [name=code]')).toHaveValue('MATH-INF100')
  await page.locator('#ntnu-fetch').click(); await page.locator('.wizard-results button').click()
  await page.getByRole('button', { name: 'Importer bare emnet' }).click()
  expect((await saved(page)).planner.courses[0]).toMatchObject({ code: 'MATH-INF100', credits: null, year: 2026, semester: 'autumn' })
})
