import { test, expect } from '@playwright/test'
import { openCourseImport, openImportMethod, openTaskDetails } from './helpers.js'

const course = { id: 'isolated-course', name: 'Isolert emne', code: 'TEST101', university: 'Testuniversitet', semester: 'autumn', year: 2026, credits: null, notes: '' }
const ics = `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Isolated E2E//EN\r\nBEGIN:VEVENT\r\nUID:isolated-event\r\nDTSTART;TZID=Europe/Oslo:20261019T100000\r\nDTEND;TZID=Europe/Oslo:20261019T110000\r\nRRULE:FREQ=WEEKLY;COUNT=2\r\nSUMMARY:Isolert forelesning\r\nLOCATION:Testrom\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`
async function seed(page, tasks = [], planner = { courses: [course], events: [], sources: [] }) {
  await page.clock.setFixedTime(new Date('2026-09-07T08:00:00Z'))
  await page.addInitScript(data => { if (!localStorage.getItem('studieplanlegger:v1')) localStorage.setItem('studieplanlegger:v1', JSON.stringify(data)) }, { schemaVersion: 1, tasks, planner })
  await page.goto('/')
}
const task = (id, patch = {}) => ({ id, title: `Isolert ${id}`, course: 'TEST101', deadlineLocal: '2026-09-08T12:00', estimatedMinutes: 30, completed: false, ...patch })

test('visible suggestions, synchronized minutes, correct task opening and delivery reminder', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message))
  await seed(page, [task('best', { remainingMinutes: 20, splittable: false, nextStep: { description: 'Teststeg', estimatedMinutes: 20 } }), task('other', { estimatedMinutes: 45, splittable: false }), task('unknown', { estimatedMinutes: null }), task('ready', { requiresSubmission: true, completed: true }), task('done', { completed: true })])
  await page.getByRole('button', { name: 'Vis forslag', exact: false }).click()
  const suggestions = page.locator('#dashboard-suggestions')
  await expect(suggestions.locator('[data-task-id="best"]')).toBeVisible()
  await expect(suggestions).toContainText('Passer innen 30 minutter')
  await expect(suggestions).toContainText('Hele oppgaven er ikke ferdig etter steget')
  await expect(page.locator('#filter-summary')).toHaveText('1 forslag innen 30 minutter.')
  await suggestions.getByRole('button', { name: 'Åpne oppgave «Isolert best»', exact: true }).click()
  await expect(page.locator('#title')).toHaveValue('Isolert best')
  await page.locator('#cancel-task').click()
  await page.locator('#available-minutes').fill('45')
  await expect(page.locator('[data-minutes="45"]')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#filter-summary')).toHaveText('2 forslag innen 45 minutter.')
  await page.locator('#toggle-alternatives').click()
  await expect(suggestions.locator('[data-task-id="other"]')).toBeVisible()
  await page.locator('[data-minutes="15"]').click()
  await expect(page.locator('#available-minutes')).toHaveValue('15')
  await expect(page.locator('#suggestion-empty')).toBeVisible()
  await page.locator('#available-minutes').fill('0')
  await expect(page.locator('#available-minutes-error')).not.toBeEmpty()
  await expect(page.locator('#delivery-reminders')).toContainText('Isolert ready')
  expect(errors).toEqual([])
})

test('manual course, teaching and unknown-duration task work without import', async ({ page }) => {
  await seed(page, [], { courses: [], events: [], sources: [] })
  await page.locator('#view-subjects').click(); await page.locator('#course-new').click()
  await page.locator('#subject-editor [name=name]').fill('Mitt testemne')
  await page.locator('#subject-editor [name=code]').fill('TEST102')
  await page.getByRole('button', { name: 'Lagre emne', exact: true }).click()
  await expect(page.locator('#course-list')).toContainText('Mitt testemne')
  await page.locator('#event-new').click()
  await page.locator('#subject-editor [name=title]').fill('Manuell testforelesning')
  await page.locator('#subject-editor [name=startLocal]').fill('2026-10-26T10:00')
  await page.locator('#subject-editor [name=endLocal]').fill('2026-10-26T11:00')
  await page.locator('#subject-editor [name=notes]').fill('Mitt notat')
  await page.getByRole('button', { name: 'Lagre undervisning', exact: true }).click()
  await expect(page.locator('#event-list')).toContainText('Manuell testforelesning')
  await page.locator('#new-task').click()
  await page.locator('#title').fill('Ukjent arbeid')
  await openTaskDetails(page)
  await page.locator('#course').fill('TEST102')
  await page.locator('#task-form button[type=submit]').click()
  await expect(page.locator('#task-form')).toBeHidden()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('studieplanlegger:v1')))
  expect(saved.tasks[0].courseId).toBe(saved.planner.courses[0].id)
  expect(saved.tasks[0].estimatedMinutes).toBeNull()
  expect(saved.planner.events[0].start).toBe('2026-10-26T09:00:00Z')
  await page.locator('#view-all').click(); await expect(page.locator('#task-list')).toContainText('Gjenstående arbeid: ukjent')
  await page.reload(); await expect(page.locator('#teaching-agenda')).toContainText('Manuell testforelesning')
})

test('ICS preview, confirmation, correct winter time, repeat import and source refresh errors', async ({ page }) => {
  await seed(page)
  await page.locator('#view-subjects').click()
  await openImportMethod(page, 'calendar')
  for (let i = 0; i < 2; i++) {
    await page.locator('[name=file]').setInputFiles({ name: 'isolated.ics', mimeType: 'text/calendar', buffer: Buffer.from(ics) })
    await page.locator('#ics-preview').click()
    await expect(page.locator('#import-preview')).toContainText('26. oktober 2026 kl. 10:00')
    if (i === 0) expect(await page.evaluate(() => JSON.parse(localStorage.getItem('studieplanlegger:v1')).planner.events.length)).toBe(0)
    await page.getByRole('button', { name: 'Bekreft import', exact: true }).click()
    await expect(page.locator('#import-preview')).toBeHidden()
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('studieplanlegger:v1')).planner.events.length)).toBe(2)
  }
  await page.locator('#view-overview').click()
  await page.getByRole('button', { name: 'Månedsvisning', exact: true }).click()
  await page.getByRole('button', { name: 'Neste måned', exact: true }).click()
  await expect(page.locator('[data-calendar-date="2026-10-26"]')).toContainText('U 1')
  await page.locator('[data-calendar-date="2026-10-26"]').click()
  await expect(page.locator('.calendar-teaching')).toContainText('10:00–11:00')
  await page.locator('.calendar-teaching [data-calendar-event]').click()
  await expect(page.locator('#subject-editor [name=startLocal]')).toHaveValue('2026-10-26T10:00')
  await page.locator('#subject-editor').getByRole('button', { name: 'Avbryt', exact: true }).click()
  await expect(page.locator('#source-list')).toContainText('Engangsimport fra fil')
  await page.route('**/api/import/calendar', route => route.fulfill({ json: { calendar: ics } }))
  await openImportMethod(page, 'calendar')
  await page.locator('#calendar-import-form [name=url]').fill('https://calendar.example.test/isolated.ics')
  await page.getByRole('button', { name: 'Hent kalenderlenke', exact: true }).click()
  await page.getByRole('button', { name: 'Bekreft import', exact: true }).click()
  await expect(page.locator('#source-list')).toContainText('Sist oppdatert')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('studieplanlegger:v1')).planner.events.length)).toBe(2)
  await page.route('**/api/import/calendar', route => route.fulfill({ status: 403, json: { error: 'Kilden krever innlogging. Last opp en .ics-fil.' } }))
  await page.getByRole('button', { name: 'Oppdater nå', exact: true }).click()
  await expect(page.locator('#subject-message')).toContainText('Last opp en .ics-fil')
  await expect(page.locator('#ics-preview')).toBeEnabled()
})

test('NTNU metadata alone remains importable when the timetable is inaccessible', async ({ page }) => {
  await seed(page, [], { courses: [], events: [], sources: [] })
  await page.route('**/api/import/providers/ntnu/search?**', route => route.fulfill({ json: { status: 'ok', results: [{ ...course, university: 'NTNU' }] } }))
  await page.route('**/api/import/providers/ntnu/details?**', route => route.fulfill({ json: { status: 'ok', course: { ...course, university: 'NTNU', sourceUrl: 'https://www.ntnu.no/studier/emner/TEST101/2026' }, calendarUrl: 'https://tp.educloud.no/ntnu/timeplan/ical.php?sem=26h', warnings: ['Studiepoeng mangler i kilden.'] } }))
  await page.route('**/api/import/calendar', route => route.fulfill({ status: 403, json: { error: 'Tilgang krever innlogging. Bruk filimport.' } }))
  await page.locator('#view-subjects').click(); await openCourseImport(page); await page.getByRole('button', { name: 'Neste: søk og semester' }).click(); await page.locator('#course-import-form [name=code]').fill('TEST101')
  await page.locator('#ntnu-fetch').click(); await page.locator('.wizard-results button').first().click(); await expect(page.locator('#import-preview')).toContainText('Studiepoeng mangler')
  await page.getByRole('button', { name: 'Hent undervisning fra TP' }).click()
  await expect(page.locator('#subject-message')).toContainText('Emneinformasjonen kan fortsatt lagres')
  await page.getByRole('button', { name: 'Importer bare emnet' }).click()
  await expect(page.locator('#course-list')).toContainText('Isolert emne')
})

test('manual editing and deletion preserve tasks, and teaching overlap can adjust the time choice', async ({ page }) => {
  await seed(page, [task('work', { courseId: course.id, remainingMinutes: 20 })])
  await page.locator('#view-subjects').click()
  await page.getByRole('button', { name: 'Rediger emne TEST101', exact: true }).click()
  await page.locator('#subject-editor [name=name]').fill('Oppdatert testemne')
  await page.locator('#subject-editor [name=notes]').fill('Eget emnenotat')
  await page.getByRole('button', { name: 'Lagre emne', exact: true }).click()
  await expect(page.locator('#course-list')).toContainText('Eget emnenotat')
  await page.locator('#event-new').click()
  await page.locator('#subject-editor [name=title]').fill('Opptatt testtid')
  await page.locator('#subject-editor [name=startLocal]').fill('2026-09-07T10:20')
  await page.locator('#subject-editor [name=endLocal]').fill('2026-09-07T11:00')
  await page.getByRole('button', { name: 'Lagre undervisning', exact: true }).click()
  await page.locator('#view-overview').click()
  await expect(page.locator('#teaching-overlap')).toContainText('Opptatt testtid')
  await page.getByRole('button', { name: 'Tilpass til 20 minutter', exact: true }).click()
  await expect(page.locator('#available-minutes')).toHaveValue('20')
  await expect(page.locator('#filter-summary')).toHaveText('1 forslag innen 20 minutter.')
  await page.locator('#view-subjects').click()
  await page.getByRole('button', { name: 'Rediger undervisning Opptatt testtid', exact: true }).click()
  await page.locator('#subject-editor [name=location]').fill('Mitt rom')
  await page.locator('#subject-editor [name=notes]').fill('Eget øktnotat')
  await page.getByRole('button', { name: 'Lagre undervisning', exact: true }).click()
  await expect(page.locator('#event-list')).toContainText('Eget øktnotat')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Slett undervisning Opptatt testtid', exact: true }).click()
  await expect(page.locator('#event-list')).toContainText('Ingen undervisning registrert')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Slett emne TEST101', exact: true }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('studieplanlegger:v1')))
  expect(saved.planner.courses).toEqual([]); expect(saved.planner.events).toEqual([])
  expect(saved.tasks).toHaveLength(1); expect(saved.tasks[0]).not.toHaveProperty('courseId')
})

test('an empty calendar link is retained and can later import newly published teaching', async ({ page }) => {
  await seed(page)
  let content = 'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Isolated E2E//EN\r\nEND:VCALENDAR\r\n'
  await page.route('**/api/import/calendar', route => route.fulfill({ json: { calendar: content } }))
  await page.locator('#view-subjects').click()
  await openImportMethod(page, 'calendar')
  await page.locator('#calendar-import-form [name=url]').fill('https://calendar.example.test/empty.ics')
  await page.getByRole('button', { name: 'Hent kalenderlenke', exact: true }).click()
  await expect(page.locator('#import-preview')).toContainText('Ingen undervisning funnet')
  await page.getByRole('button', { name: 'Bekreft import', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Oppdater nå', exact: true })).toBeVisible()
  content = ics
  await page.getByRole('button', { name: 'Oppdater nå', exact: true }).click()
  await page.locator('.activity-choices input').check()
  await page.getByRole('button', { name: 'Bekreft import', exact: true }).click()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('studieplanlegger:v1')).planner.events.length)).toBe(2)
})
