import { expectModal } from './helpers.js'
import { navigate } from './helpers.js'
import { openMenu, openTaskDetails } from './helpers.js'
import { test, expect } from '@playwright/test'
import { task, seed, rows, row, checkbox, edit, save, raw, saved, writes, ids, filter, showAlternatives, deleteTask, fillDraft } from './helpers.js'

const choices = [
  task('future-20', '2026-10-25T02:30', 20),
  task('tie-first-30', '2026-09-03T12:00', 30),
  task('old-20', '2026-08-01T12:00', 20),
  task('late-20', '2026-09-03T23:59', 20),
  task('tie-second-20', '2026-09-03T12:00', 20),
  { ...task('too-long-31', '2026-09-01T12:00', 31), splittable: false },
  task('done-20', '2026-08-01T12:00', 20, true),
]
const expectedIds = ['old-20', 'tie-first-30', 'tie-second-20', 'late-20', 'future-20']

test('30 minutes includes 20/30 across all weeks and overdue tasks, excludes 31/completed, and orders deadlines before durations', async ({ page }, testInfo) => {
  await seed(page, choices)
  const before = await raw(page)
  await filter(page)
  await expect(page.locator('#view-time')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#view-week')).toHaveAttribute('aria-pressed', 'false')
  expect(await ids(page)).toEqual(expectedIds)
  await expect(page.locator('#filter-summary')).toHaveText('5 forslag innen 30 minutter.')
  await expect(row(page, choices[2].title).getByText('Forfalt', { exact: true })).toBeVisible()
  await navigate(page, 'all')
  await expect(rows(page)).toHaveCount(choices.length)
  await navigate(page, 'week')
  await navigate(page, 'time')
  await expect(page.locator('#available-minutes')).toHaveValue('30')
  expect(await ids(page)).toEqual(expectedIds)
  // Valid custom input updates the same selection used by quick choices and results.
  await page.locator('#available-minutes').fill('45')
  await navigate(page, 'week')
  await navigate(page, 'time')
  await expect(page.locator('#available-minutes')).toHaveValue('45')
  await expect(page.locator('#filter-summary')).toContainText('45 minutter')
  expect(await ids(page)).toEqual(['old-20', 'too-long-31', 'tie-first-30', 'tie-second-20', 'late-20', 'future-20'])
  await page.locator('#available-minutes').focus()
  await page.locator('#filter-summary').evaluate(element => {
    window.summaryMutations = []
    window.summaryObserver = new MutationObserver(records => window.summaryMutations.push(...records.map(record => record.type)))
    window.summaryObserver.observe(element, { childList: true, characterData: true, subtree: true })
  })
  await page.clock.runFor(2000)
  expect(await page.evaluate(() => window.summaryMutations)).toEqual([])
  await page.evaluate(() => window.summaryObserver.disconnect())
  await expect(page.locator('#available-minutes')).toHaveValue('45')
  await expect(page.locator('#available-minutes')).toBeFocused()
  expect(await raw(page)).toBe(before)
  expect(await saved(page)).toEqual({ schemaVersion: 1, tasks: choices })
  expect(await writes(page)).toEqual([])
  await page.reload()
  await expect(page.locator('#view-overview')).toHaveAttribute('aria-pressed', 'true')
  await navigate(page, 'time')
  await expect(page.locator('#available-minutes')).toHaveValue('30')
  expect(await ids(page)).toEqual(expectedIds)
  expect(await saved(page)).toEqual({ schemaVersion: 1, tasks: choices })
})

test('invalid minutes retain field input and task data, hide stale hits, and recover only on valid resubmission', async ({ page }, testInfo) => {
  await seed(page, choices)
  const before = await raw(page)
  for (const minutes of ['', '0', '-1', '1.5', '2e2', '9007199254740992', 'NaN', ' ']) {
    await filter(page, '30')
    expect(await ids(page)).toEqual(expectedIds)
    await page.locator('#available-minutes').fill(minutes)
    await page.locator('#available-minutes').press('Enter')
    await expect(page.locator('#available-minutes')).toHaveValue(minutes)
    await expect(page.locator('#available-minutes')).toBeFocused()
    await expect(page.locator('#available-minutes')).toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator('#available-minutes')).toHaveAttribute('aria-describedby', 'available-minutes-error')
    await expect(page.locator('#available-minutes-error')).not.toHaveText('')
    await expect(rows(page)).toHaveCount(0)
    await expect(page.locator('#empty-tasks')).not.toBeVisible()
    await page.clock.runFor(1000)
    await expect(rows(page)).toHaveCount(0)
    await expect(page.locator('#available-minutes')).toBeFocused()
    await navigate(page, 'all')
    await expect(rows(page)).toHaveCount(choices.length)
    await navigate(page, 'time')
    await expect(page.locator('#available-minutes')).toHaveValue(minutes)
    await expect(rows(page)).toHaveCount(0)
  }
  await filter(page, '30')
  await expect(page.locator('#available-minutes')).toHaveAttribute('aria-invalid', 'false')
  await expect(page.locator('#available-minutes-error')).toHaveText('')
  expect(await ids(page)).toEqual(expectedIds)
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
})

test('empty time result offers keyboard change-minutes and all-tasks routes without writes', async ({ page }, testInfo) => {
  await seed(page, choices.map(task => ({ ...task, splittable: false })))
  await filter(page, '1')
  await expect(rows(page)).toHaveCount(0)
  await expect(page.locator('#empty-tasks')).toContainText('Ingen oppgaver passer tiden')
  await page.locator('#empty-minutes').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#available-minutes')).toBeFocused()
  await page.locator('#available-minutes').fill('30')
  await page.keyboard.press('Enter')
  expect(await ids(page)).toEqual(expectedIds)
  await filter(page, '1')
  await page.locator('#empty-all').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#view-all')).toBeFocused()
  await expect(page.locator('#view-all')).toHaveAttribute('aria-pressed', 'true')
  await expect(rows(page)).toHaveCount(choices.length)
  expect(await writes(page)).toEqual([])
})

test('completion removes a hit with relevant focus, undo restores eligibility and tied order survives edit and reopen', async ({ page, context }, testInfo) => {
  await seed(page, choices)
  await filter(page)
  const selected = choices[1]
  await openMenu(page, selected.title)
  await checkbox(page, selected.title).focus()
  await page.keyboard.press('Space')
  expect(await ids(page)).toEqual(expectedIds.filter(id => id !== selected.id))
  await expect(page.locator('#filter-summary')).toHaveText('4 forslag innen 30 minutter.')
  await expect(checkbox(page, choices[4].title)).toBeFocused()
  await navigate(page, 'all')
  await expect(checkbox(page, selected.title)).toBeChecked()
  await page.locator('.contextual-undo').getByRole('button', { name: 'Angre siste endring' }).click()
  await navigate(page, 'time')
  expect(await ids(page)).toEqual(expectedIds)
  await showAlternatives(page)
  await openMenu(page, selected.title)
  await edit(page, selected.title).click()
  await page.locator('#course').fill('Rettet emne')
  await save(page).click()
  expect(await ids(page)).toEqual(expectedIds)
  expect((await saved(page)).tasks.map(item => item.id)).toEqual(choices.map(item => item.id))
  expect(await writes(page)).toHaveLength(3)
  await page.close()
  const reopened = await context.newPage()
  await reopened.goto('/')
  await filter(reopened)
  expect(await ids(reopened)).toEqual(expectedIds)
  await expect(row(reopened, selected.title)).toContainText('Rettet emne')
  await expect(checkbox(reopened, selected.title)).not.toBeChecked()
})

test('active filter keeps hits/raw state on failed completion, edit or delete and updates only after retries succeed', async ({ page }, testInfo) => {
  const a = task('a', '2026-08-31T12:00', 20)
  const b = { ...task('b', '2026-09-03T12:00', 30), splittable: false }
  const c = task('c', '2026-10-25T02:30', 30)
  await seed(page, [a, b, c])
  await filter(page)
  let before = await raw(page)
  await page.evaluate(() => { window.failWrite = true })
  await openMenu(page, a.title)
  await checkbox(page, a.title).click()
  await expect(checkbox(page, a.title)).not.toBeChecked()
  await expect(checkbox(page, a.title)).toBeFocused()
  expect(await ids(page)).toEqual([a.id, b.id, c.id])
  expect(await raw(page)).toBe(before)
  await page.evaluate(() => { window.failWrite = false })
  await openMenu(page, a.title)
  await checkbox(page, a.title).click()
  expect(await ids(page)).toEqual([b.id, c.id])
  await expect(checkbox(page, b.title)).toBeFocused()
  before = await raw(page)
  await openMenu(page, b.title)
  await edit(page, b.title).click()
  await page.locator('#remainingMinutes').fill('31')
  await page.evaluate(() => { window.failWrite = true })
  await save(page).click()
  await expect(page.getByRole('status')).toContainText('Endringen ble ikke lagret')
  await expect(page.locator('#remainingMinutes')).toHaveValue('31')
  await expect(row(page, b.title)).toContainText('Hele oppgaven: 30 min')
  expect(await ids(page)).toEqual([b.id, c.id])
  expect(await raw(page)).toBe(before)
  await page.clock.runFor(2000)
  await expect(page.locator('#remainingMinutes')).toHaveValue('31')
  await expect(save(page)).toBeFocused()
  await page.evaluate(() => { window.failWrite = false })
  await save(page).click()
  expect(await ids(page)).toEqual([c.id])
  await expect(page.getByRole('status')).toHaveText('Endringer lagret. Du finner oppgaven under «Alle oppgaver».')
  await expect(page.locator('#available-minutes')).toBeFocused()
  before = await raw(page)
  await deleteTask(page, c.title, false)
  expect(await raw(page)).toBe(before)
  expect(await ids(page)).toEqual([c.id])
  await page.evaluate(() => { window.failWrite = true })
  await deleteTask(page, c.title)
  await expect(row(page, c.title)).toContainText('Oppgaven ble ikke slettet')
  expect(await ids(page)).toEqual([c.id])
  expect(await raw(page)).toBe(before)
  await page.evaluate(() => { window.failWrite = false })
  await deleteTask(page, c.title)
  await expect(rows(page)).toHaveCount(0)
  await expect(page.locator('#empty-tasks')).toContainText('Ingen oppgaver passer tiden')
  await expect(page.locator('#available-minutes')).toBeFocused()
  expect((await saved(page)).tasks).toEqual([{ ...a, completed: true, remainingMinutes: 0 }, { ...b, remainingMinutes: 31 }])
  expect(await writes(page)).toHaveLength(6)
})

test('creating outside the available minutes keeps the empty filter and explains where the saved task is', async ({ page }, testInfo) => {
  await seed(page, [], { view: 'time' })
  await expect(page.locator('#empty-dashboard')).toBeVisible()
  await expect(page.locator('#focus-panel')).toBeHidden()
  const draft = { title: 'Trenger mer tid', course: 'IBE160', deadlineLocal: '2026-09-03T12:00', estimatedMinutes: '31' }
  await page.locator('#empty-onboard-task').click()
  await fillDraft(page, draft)
  await openTaskDetails(page)
  await page.locator('[name=splittable]').uncheck()
  await save(page).click()
  await expect(page.locator('#view-time')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#available-minutes')).toHaveValue('30')
  await expect(rows(page)).toHaveCount(0)
  await expect(page.locator('#empty-tasks')).toContainText('Ingen oppgaver passer tiden')
  await expect(page.getByRole('status')).toHaveText('Oppgave lagret. Du finner oppgaven under «Alle oppgaver».')
  expect((await saved(page)).tasks).toHaveLength(1)
  expect(await writes(page)).toHaveLength(1)
  await page.locator('#empty-all').click()
  await expect(row(page, draft.title)).toContainText('Gjenstående arbeid: 31 min')
})

test('task dialog blocks background task, calendar and navigation actions in each view without writes', async ({ page }, testInfo) => {
  const existing = task('too-long', '2026-09-03T15:00', 31)
  await seed(page, [existing])
  const before = await raw(page)
  for (const view of ['time', 'all']) {
    await navigate(page, view)
    await page.locator('#new-task').click()
    await page.locator('#title').fill('Ulagret oppgave')
    await expectModal(page, 'task-form')
    await expect(page.locator('#draft-info')).toBeHidden()
    await page.clock.runFor(2000)
    await expectModal(page, 'task-form')
    await expect(page.locator('#title')).toHaveValue('Ulagret oppgave')
    await expect(page.locator('#view-' + view)).toHaveAttribute('aria-pressed', 'true')
    for (const control of await rows(page).locator('button, input[type=checkbox]').all()) await expect(control).toBeDisabled()
    const calendarEdit = page.locator('#compact-agenda [data-agenda-key="task:too-long"]')
    await expect(calendarEdit).toHaveCount(1)
    await page.locator('#title').focus()
    await calendarEdit.focus()
    await expect(page.locator('#title')).toBeFocused()
    await page.locator('#cancel-task').focus()
    await page.keyboard.press('Tab')
    await expect(page.locator('#title')).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(page.locator('#cancel-task')).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(page.locator('dialog[open]')).toHaveCount(0)
    await expect(page.locator('#new-task')).toBeFocused()
    expect(await raw(page)).toBe(before)
    expect(await writes(page)).toEqual([])
  }
})
