const localOrigin = `http://127.0.0.1:${process.env.PLAYWRIGHT_PORT || '5174'}`
import { expectModal } from './helpers.js'
import { navigate } from './helpers.js'
import { openMenu, deadlineLabel } from './helpers.js'
import { test, expect } from '@playwright/test'
import { task, seed, rows, row, checkbox, edit, saved, raw, writes, ids, fillDraft, save, expectFocusFits } from './helpers.js'

const weeks = [
  { name: 'month boundary', now: '2026-09-02T12:00:00+02:00', previous: '2026-08-30T23:59', start: '2026-08-31T00:00', middle: '2026-09-02T12:00', end: '2026-09-06T23:59', next: '2026-09-07T00:00' },
  { name: 'year boundary', now: '2027-01-01T12:00:00+01:00', previous: '2026-12-27T23:59', start: '2026-12-28T00:00', middle: '2027-01-01T12:00', end: '2027-01-03T23:59', next: '2027-01-04T00:00' },
  { name: 'spring DST week', now: '2026-03-25T12:00:00+01:00', previous: '2026-03-22T23:59', start: '2026-03-23T00:00', middle: '2026-03-25T12:00', end: '2026-03-29T23:59', next: '2026-03-30T00:00' },
  { name: 'autumn DST week', now: '2026-10-23T12:00:00+02:00', previous: '2026-10-18T23:59', start: '2026-10-19T00:00', middle: '2026-10-23T12:00', end: '2026-10-25T23:59', next: '2026-10-26T00:00' },
]

for (const week of weeks) {
  test(`initial week includes local Monday through Sunday at ${week.name}; all view preserves source order`, async ({ page }, testInfo) => {
    const previous = task('previous', week.previous)
    const start = task('start', week.start)
    const middle = task('completed', week.middle, 30, true)
    const end = task('end', week.end)
    const next = task('next', week.next)
    const source = [next, middle, end, previous, start]
    await seed(page, source, { now: week.now })
    const before = await raw(page)
    await expect(page.locator('#view-week')).toHaveAttribute('aria-pressed', 'true')
    await expect(page.locator('#view-all')).toHaveAttribute('aria-pressed', 'false')
    await expect(page.locator('#view-time')).toHaveAttribute('aria-pressed', 'false')
    expect(await ids(page)).toEqual([start.id, middle.id, end.id])
    await expect(checkbox(page, middle.title)).toBeChecked()
    await expect(row(page, middle.title)).toContainText('Fullført')
    await expect(row(page, middle.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
    await expect(page.locator('#overdue-count')).toContainText('2')
    await page.locator('#overdue-all').click()
    await expect(page.locator('#view-all')).toHaveAttribute('aria-pressed', 'true')
    expect(await ids(page)).toEqual([previous.id, start.id, middle.id, end.id, next.id])
    for (const item of source) await expect(row(page, item.title)).toContainText(deadlineLabel(item.deadlineLocal, Number(week.now.slice(0, 4))))
    await expect(row(page, previous.title).getByText('Forfalt', { exact: true })).toBeVisible()
    await navigate(page, 'week')
    expect(await ids(page)).toEqual([start.id, middle.id, end.id])
    expect((await saved(page)).tasks).toEqual(source)
    expect(await raw(page)).toBe(before)
    expect(await writes(page)).toEqual([])
  })
}

test('strict deadline transition patches the same checkbox, preserves focus and never writes', async ({ page }, testInfo) => {
  const open = task('due', '2026-09-03T12:00')
  const done = task('done', open.deadlineLocal, 30, true)
  await seed(page, [open, done], { now: '2026-09-03T11:59:59+02:00' })
  const before = await raw(page)
  const control = checkbox(page, open.title)
  await openMenu(page, open.title)
  await expect(page.locator('#overdue-count')).toHaveAttribute('aria-live', 'polite')
  await expect(page.locator('#overdue-count')).toHaveAttribute('aria-atomic', 'true')
  await expect(page.locator('#overdue-count')).toHaveText('0 forfalte oppgaver på tvers av alle uker.')
  await page.locator('#overdue-count').evaluate(element => {
    window.overdueMutations = 0
    window.overdueObserver = new MutationObserver(records => { window.overdueMutations += records.length })
    window.overdueObserver.observe(element, { childList: true, characterData: true, subtree: true })
  })
  await control.focus()
  await control.evaluate(element => { window.originalCheckbox = element; window.originalRow = element.closest('li') })
  await expect(row(page, open.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  await page.clock.runFor(1000)
  await expect(row(page, open.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  expect(await page.evaluate(() => window.overdueMutations)).toBe(0)
  await page.evaluate(() => window.overdueObserver.disconnect())
  await expect(row(page, done.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  await page.clock.runFor(1000)
  await expect(row(page, open.title).getByText('Forfalt', { exact: true })).toBeVisible()
  await expect(page.locator('#overdue-count')).toHaveText('1 forfalte oppgaver på tvers av alle uker.')
  await expect(row(page, done.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  await expect(control).toBeFocused()
  await expectFocusFits(page, control)
  expect(await control.evaluate(element => element === window.originalCheckbox && element.closest('li') === window.originalRow)).toBe(true)
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
  // A deliberate scroll away from the focused field must survive later ticks.
  await page.setViewportSize({ width: 1280, height: 400 })
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await control.evaluate(element => element.getBoundingClientRect().top > innerHeight)).toBe(true)
  const scrollBeforeTick = await page.evaluate(() => scrollY)
  await page.clock.runFor(1000)
  await expect(control).toBeFocused()
  expect(await page.evaluate(() => scrollY)).toBe(scrollBeforeTick)
  expect(await writes(page)).toEqual([])
  // Completion and undo update the count immediately in the current week.
  await page.keyboard.press('Space')
  await expect(row(page, open.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  await page.keyboard.press('Space')
  await expect(row(page, open.title).getByText('Forfalt', { exact: true })).toBeVisible()
  expect(await writes(page)).toHaveLength(2)
})

for (const mode of ['create', 'edit']) {
  test(`${mode} draft, field error and focused control survive deadline and week rollover`, async ({ page }, testInfo) => {
    const previous = task('sunday', '2026-09-06T23:59')
    const following = task('monday', '2026-09-07T00:00')
    await seed(page, [previous, following], { now: '2026-09-06T23:59:59+02:00' })
    const before = await raw(page)
    if (mode === 'create') await page.locator('#new-task').click()
    else { await openMenu(page, previous.title); await edit(page, previous.title).click() }
    const draft = { title: ' ', course: 'Ulagret emne', deadlineLocal: '2026-10-25T02:30', remainingMinutes: '15' }
    await fillDraft(page, draft)
    await save(page).click()
    const error = await page.locator('#title-error').textContent()
    await expect(page.locator('#title')).toBeFocused()
    await page.clock.runFor(2000)
    expect(await ids(page)).toEqual([following.id])
    await expect(page.locator('#task-form')).toBeVisible()
    for (const [field, value] of Object.entries(draft)) await expect(page.locator(`#${field}`)).toHaveValue(value)
    await expect(page.locator('#title')).toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator('#title-error')).toHaveText(error)
    await expect(page.locator('#title')).toBeFocused()
    for (const control of await rows(page).locator('button, input[type=checkbox]').all()) await expect(control).toBeDisabled()
    await expect(row(page, following.title).getByText('Forfalt', { exact: true })).toBeVisible()
    await expect(page.locator('#overdue-count')).toContainText('2')
    expect(await raw(page)).toBe(before)
    expect(await writes(page)).toEqual([])
    await page.locator('#cancel-task').click()
    expect(await page.evaluate(() => document.activeElement?.isConnected && document.activeElement.matches('button, input'))).toBe(true)
    for (const control of await rows(page).locator('button:visible, input[type=checkbox]:visible').all()) await expect(control).toBeEnabled()
    await page.locator('#overdue-all').click()
    expect(await ids(page)).toEqual([previous.id, following.id])
    await expect(row(page, previous.title).getByText('Forfalt', { exact: true })).toBeVisible()
    expect(await writes(page)).toEqual([])
  })
}

test('week rollover moves focus from a departing row and keeps older overdue tasks reachable', async ({ page }, testInfo) => {
  const old = task('old', '2026-09-06T23:59')
  const next = task('next', '2026-09-07T00:00')
  await seed(page, [old, next], { now: '2026-09-06T23:59:59+02:00' })
  await openMenu(page, old.title)
  await checkbox(page, old.title).focus()
  await page.clock.runFor(1000)
  expect(await ids(page)).toEqual([next.id])
  await expect(row(page, next.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  expect(await page.evaluate(() => {
    const active = document.activeElement
    return active?.isConnected && active.matches('button, input') && !active.disabled && !active.closest('[hidden]')
  })).toBe(true)
  await expect(page.locator('#overdue-count')).toContainText('1')
  await page.locator('#overdue-all').click()
  await expect(row(page, old.title).getByText('Forfalt', { exact: true })).toBeVisible()
  expect(await writes(page)).toEqual([])
})

test('focus, visibility and view actions refresh a jumped clock without a timer or storage write', async ({ page }, testInfo) => {
  const due = task('focus', '2026-09-03T12:00')
  await seed(page, [due], { now: '2026-09-03T11:59:59+02:00' })
  const before = await raw(page)
  await page.clock.setSystemTime(new Date('2026-09-03T12:00:01+02:00'))
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(row(page, due.title).getByText('Forfalt', { exact: true })).toBeVisible()
  await page.clock.setSystemTime(new Date('2026-09-03T11:59:59+02:00'))
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')))
  await expect(row(page, due.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  await page.clock.setSystemTime(new Date('2026-09-03T12:00:01+02:00'))
  await navigate(page, 'all')
  await expect(row(page, due.title).getByText('Forfalt', { exact: true })).toBeVisible()
  await page.clock.setSystemTime(new Date('2026-09-03T11:59:59+02:00'))
  await openMenu(page, due.title)
  await edit(page, due.title).click()
  await page.locator('#course').fill('Ulagret mens siden er skjult')
  await expect(page.locator('#course')).toBeFocused()
  await expect(row(page, due.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  // Simulate Page Visibility API state; this does not minimize a physical browser window.
  await page.evaluate(() => {
    window.simulatedHidden = true
    Object.defineProperty(document, 'hidden', { configurable: true, get: () => window.simulatedHidden })
    Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => window.simulatedHidden ? 'hidden' : 'visible' })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await page.clock.runFor(2000)
  await expect(row(page, due.title).getByText('Forfalt', { exact: true })).not.toBeVisible()
  await expect(page.locator('#course')).toHaveValue('Ulagret mens siden er skjult')
  await expect(page.locator('#course')).toBeFocused()
  expect(await writes(page)).toEqual([])
  await page.evaluate(() => {
    window.simulatedHidden = false
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await expect(row(page, due.title).getByText('Forfalt', { exact: true })).toBeVisible()
  await expect(page.locator('#course')).toHaveValue('Ulagret mens siden er skjult')
  await expect(page.locator('#course')).toBeFocused()
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
})

test('an empty week gaining tasks at Monday rollover moves focus off the hidden empty-state shortcut', async ({ page }, testInfo) => {
  const next = task('new-week', '2026-09-07T00:00')
  await seed(page, [next], { now: '2026-09-06T23:59:59+02:00' })
  const before = await raw(page)
  await page.locator('#empty-all').focus()
  await expect(page.locator('#empty-all')).toBeFocused()
  await page.clock.runFor(1000)
  await expect(page.locator('#empty-tasks')).toBeHidden()
  await expect(edit(page, next.title)).toBeFocused()
  await expect(edit(page, next.title)).toBeInViewport({ ratio: 1 })
  expect(await ids(page)).toEqual([next.id])
  expect(await raw(page)).toBe(before)
  expect(await writes(page)).toEqual([])
})

test('saving and editing a task outside the week keeps the view and explains the all-tasks route', async ({ page }, testInfo) => {
  await seed(page, [])
  const draft = { title: 'Neste uke', course: 'IBE160', deadlineLocal: '2026-09-07T12:00', estimatedMinutes: '30' }
  await page.locator('#new-task').click()
  await fillDraft(page, draft)
  await save(page).click()
  await expect(page.locator('#view-week')).toHaveAttribute('aria-pressed', 'true')
  await expect(rows(page)).toHaveCount(0)
  await expect(page.locator('#empty-tasks')).toBeVisible()
  await expect(page.getByRole('status')).toHaveText('Oppgave lagret. Du finner oppgaven under «Alle oppgaver».')
  expect((await saved(page)).tasks).toHaveLength(1)
  expect(await writes(page)).toHaveLength(1)
  await page.locator('#empty-all').click()
  await expect(row(page, draft.title)).toBeVisible()
  await navigate(page, 'week')
  // The upcoming agenda can open a task whose deadline is outside this week.
  await page.locator('#compact-agenda .agenda-entry').filter({ hasText: draft.title }).click()
  await expectModal(page, 'task-form')
  await page.locator('#course').fill('Rettet emne')
  await save(page).click()
  await expect(page.locator('#view-week')).toHaveAttribute('aria-pressed', 'true')
  await expect(rows(page)).toHaveCount(0)
  await expect(page.getByRole('status')).toHaveText('Endringer lagret. Du finner oppgaven under «Alle oppgaver».')
  await page.locator('#overdue-all').click()
  await expect(row(page, draft.title)).toContainText('Rettet emne')
  expect(await writes(page)).toHaveLength(2)
})

test('an empty week explains both routes and view selection is not persisted', async ({ page }, testInfo) => {
  const distant = task('future', '2026-10-25T02:30')
  await seed(page, [distant])
  await expect(rows(page)).toHaveCount(0)
  await expect(page.locator('#empty-tasks')).toBeVisible()
  await expect(page.locator('#empty-tasks')).toContainText(/uken/i)
  await expect(page.locator('#new-task')).toBeEnabled()
  await page.locator('#new-task').click()
  await expect(page.locator('#title')).toBeFocused()
  await page.locator('#cancel-task').click()
  await page.locator('#empty-all').click()
  await expect(row(page, distant.title)).toBeVisible()
  await openMenu(page, distant.title)
  await checkbox(page, distant.title).check()
  await expect(row(page, distant.title)).toContainText('Fullført')
  await openMenu(page, distant.title)
  await checkbox(page, distant.title).uncheck()
  await page.reload()
  await expect(page.locator('#view-overview')).toHaveAttribute('aria-pressed', 'true')
  await navigate(page, 'week')
  await expect(rows(page)).toHaveCount(0)
  const { history, ...data } = await saved(page)
  expect(data).toMatchObject({ schemaVersion: 1, tasks: [{ ...distant, remainingMinutes: null }] })
  expect(data.workLogs).toHaveLength(1)
  expect(data.workLogs[0]).toMatchObject({ taskId: distant.id, outcome: 'done', remainingMinutes: 0, actualMinutes: null })
  expect(history.undo).toHaveLength(2)
  expect(await writes(page)).toEqual([])
})

test('repeated Oslo minutes compare current wall time before, exactly at and after both occurrences', async ({ page }, testInfo) => {
  const repeated = task('repeated', '2026-10-25T02:30')
  await seed(page, [repeated], { now: '2026-10-25T02:29:59+02:00' })
  const control = checkbox(page, repeated.title)
  await openMenu(page, repeated.title)
  const overdue = row(page, repeated.title).getByText('Forfalt', { exact: true })
  await control.focus()
  await expect(overdue).not.toBeVisible()
  await page.clock.runFor(1000)
  await expect(overdue).not.toBeVisible()
  await page.clock.runFor(1000)
  await expect(overdue).toBeVisible()
  await page.clock.setSystemTime(new Date('2026-10-25T02:15:00+01:00'))
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(overdue).not.toBeVisible()
  await page.clock.setSystemTime(new Date('2026-10-25T02:30:00+01:00'))
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(overdue).not.toBeVisible()
  await page.clock.runFor(1000)
  await expect(overdue).toBeVisible()
  await expect(control).toBeFocused()
  await expect(row(page, repeated.title)).toContainText('25. oktober kl. 02:30')
  expect((await saved(page)).tasks).toEqual([repeated])
  expect(await writes(page)).toEqual([])
})

test('changing browser timezone preserves saved wall-clock labels, edit draft and focus without writes', async ({ browser }, testInfo) => {
  // Explicit undefined prevents Playwright from injecting its fixed Oslo fixture default.
  // One CDP session instead owns both timezones, with Oslo set and checked before the switch.
  const context = await browser.newContext({ baseURL: localOrigin, timezoneId: undefined })
  const page = await context.newPage()
  const cdp = await context.newCDPSession(page)
  try {
    await cdp.send('Emulation.setTimezoneOverride', { timezoneId: 'Europe/Oslo' })
    const repeated = task('wall-clock', '2026-10-25T02:30')
    await seed(page, [repeated], { view: 'all', now: '2026-10-25T03:00:00+01:00' })
    expect(await page.evaluate(() => Intl.DateTimeFormat().resolvedOptions().timeZone)).toBe('Europe/Oslo')
    const before = await raw(page)
    await openMenu(page, repeated.title)
    await edit(page, repeated.title).click()
    await page.locator('#course').fill('Ulagret emne')
    await page.locator('#deadlineTime').focus()
    await cdp.send('Emulation.setTimezoneOverride', { timezoneId: '' })
    await cdp.send('Emulation.setTimezoneOverride', { timezoneId: 'America/New_York' })
    await page.evaluate(() => window.dispatchEvent(new Event('focus')))
    expect(await page.evaluate(() => Intl.DateTimeFormat().resolvedOptions().timeZone)).toBe('America/New_York')
    await page.clock.runFor(2000)
    await expect(page.locator('#deadlineLocal')).toHaveValue('2026-10-25T02:30')
    await expect(page.locator('#deadlineTime')).toBeFocused()
    await expect(page.locator('#course')).toHaveValue('Ulagret emne')
    await expect(row(page, repeated.title)).toContainText('25. oktober kl. 02:30')
    expect(await raw(page)).toBe(before)
    expect(await writes(page)).toEqual([])
  } finally { await context.close() }
})
