import {createHash} from 'node:crypto'
import {load,clean,fail,cachedText,restrictedUrl} from './program-source.js'
import {readPublicPdfItems} from './public-pdf-text.js'
import {sourceEdition,studentCohort} from './current-program-source.js'
export const onhArchiveUrl='https://oslonyehoyskole.no/Studentinfo/Studieplaner'
const archiveGuard=input=>restrictedUrl(input,{origin:'https://oslonyehoyskole.no',paths:[/^\/Studentinfo\/Studieplaner\/?$/]})
const digest=value=>createHash('sha256').update(value).digest('hex').slice(0,16)
export function onhPdfUrl(input){return restrictedUrl(input,{origin:'https://s3.eu-west-1.amazonaws.com',paths:[/^\/bhi\.no\/.+\.pdf$/i],keys:['VersionId']})}
const normalize=name=>clean(name).normalize('NFC').toLocaleLowerCase('nb').replace(/^studieplan(?:en)?\s+(?:for\s+)?/,'').replace(/(?:20\d{2}\s*[/–-]\s*(?:20)?\d{2}).*$/,'').replace(/(?:\s+med fordypning|:\s*fordypning|\s+på nett|\s+-\s+nettstudium).*$/,'').replace(/[_–-]/g,' ').replace(/[^\p{L}\d ]/gu,'').replace(/\s+/g,' ').trim()
export function parseOnhArchive(html,selected){const $=load(html),rows=new Map(),wanted=normalize(selected.name);$('a[href]').each((_,node)=>{const label=clean($(node).text()),year=label.match(/(20\d{2})\s*[/–-]\s*(20\d{2})/);if(!/^Studieplan/i.test(label)||!year||+year[2]!==+year[1]+1||normalize(label)!==wanted)return;let url;try{url=onhPdfUrl($(node).attr('href'))}catch{return}if(!rows.has(url.href))rows.set(url.href,{cohort:`edition-${year[1]}-${digest(url.href)}`,label:`${label} · kildeutgave, oppgi eget kull`,requiresStudentCohort:true,sourceUrl:url.href,academicYear:`${year[1]}/${year[2]}`,archiveLabel:label})});return [...rows.values()]}
export async function onhPdfEditions(fetchText,selected){return parseOnhArchive(await cachedText(fetchText,onhArchiveUrl,archiveGuard),selected)}
const ordinals={første:1,andre:2,tredje:3,fjerde:4,femte:5,sjette:6,sjuende:7,syvende:7,åttende:8}
const pdfText=value=>clean(value).replace(/\b([A-ZÆØÅ]{2,10})\s*(\d(?:\s*\d){2,5})\b/g,(_,letters,numbers)=>letters+numbers.replace(/\s/g,''))
function placement(raw){let text=clean(raw).toLocaleLowerCase('nb');for(const[word,n]of Object.entries(ordinals))text=text.replace(new RegExp(`\\b${word}\\b`,'g'),String(n));const values=[...text.matchAll(/\b(\d{1,2})\.?/g)].map(m=>+m[1]).filter(n=>n>0&&n<=40);if(/studieår|studieåret/.test(text)){const semesters=[...new Set(values.flatMap(n=>[n*2-1,n*2]))].filter(n=>n<=40);return {semesters,clarified:true}}if(!/semester/.test(text)||!values.length)return{semesters:[],clarified:true};if(/[-–]/.test(text)&&values.length===2){if(values[1]<values[0])return{semesters:[],clarified:true};return{semesters:Array.from({length:values[1]-values[0]+1},(_,n)=>values[0]+n),clarified:true}}return{semesters:[...new Set(values)],clarified:values.length>1||/eller|valgfri|kan/i.test(text)}}
export function parseOnhPdf(pages,selected,edition,cohort){
  const cover=clean(pages.slice(0,2).flatMap(p=>p.items.map(i=>i.str)).join(' ')),years=edition.academicYear.split('/'),short=`${years[0].slice(2)}/${years[1].slice(2)}`
  if(!cover.includes(edition.academicYear)&&!cover.includes(edition.academicYear.replace('/','-'))&&!cover.includes(short))fail('source-changed','PDF-forsiden bekrefter ikke den valgte publiserte planutgaven.')
  const documents=pages.map(p=>({page:p.page,text:pdfText(p.items.filter(i=>!(i.transform[5]<75&&/^\d+$/.test(i.str))&&!/^Studieplan for .*20\d{2}/i.test(i.str)).map(i=>i.str).join(' '))})),text=documents.map(p=>p.text).join('\n').replace(/\b([A-ZÆØÅ]{2,10})\s*(\d(?:\s*\d){2,5})\b/g,(_,letters,numbers)=>letters+numbers.replace(/\s/g,'')),headings=[...text.matchAll(/\b\d+(?:\.\d+){1,4}\.?\s+([A-ZÆØÅ]{2,10}\d{3,5}[A-Z]?)\s+/g)].filter(m=>{const nearby=text.slice(m.index,m.index+2000);return !/\.{4}/.test(nearby.slice(0,200))&&/Studiepoeng\s*:/.test(nearby)}),metadata=[...text.matchAll(/Emne(?:kode)?\s*:\s*([A-ZÆØÅ]{2,10}\d{3,5}[A-Z]?)\s+/g)].filter(m=>/Studiepoeng\s*:/.test(text.slice(m.index,m.index+500))&&!headings.some(h=>h[1]===m[1]&&h.index<m.index&&m.index-h.index<2000)),anchors=[...headings,...metadata].sort((a,b)=>a.index-b.index),courses=[],warnings=[],seen=new Set(),choiceGroups=[...text.matchAll(/\b(\d+(?:\.\d+)*)\.?\s+(?:Valgfrie emner|Valgemner)\b/gi)].filter(m=>!text.slice(m.index,m.index+150).includes('....')).map(m=>({prefix:m[1].replace(/\.0$/,''),intro:text.slice(m.index,anchors.find(a=>a.index>m.index)?.index??m.index+1500)}))
  for(const[index,anchor]of anchors.entries()){
    const section=text.slice(anchor.index,anchors[index+1]?.index??text.length),metaEnd=section.search(/Studiepoeng\s*:/),header=clean(section.slice(0,metaEnd)),code=anchor[1],sectionNumber=anchor[0].match(/^\d+(?:\.\d+)*/)?.[0],group=choiceGroups.find(g=>sectionNumber?.startsWith(g.prefix+'.')),groupYear=group?.intro.match(/(?:første|andre|tredje|fjerde|\d+\.?)\s+studieår(?:et)?/i)?.[0],explicitCode=header.match(/Emne(?:kode)?\s*:\s*([A-ZÆØÅ]{2,10}\d{3,5}[A-Z]?)/)?.[1],metaName=header.match(/Tittel\s*:\s*(.+?)(?=\s+(?:Undertittel|Type|Plassering|Undervisningsspråk)\s*:?|$)/)?.[1],heading=clean(header.slice(anchor[0].length).split(/\s+(?:Emne(?:kode)?|Tittel|Type|Plassering)\s*:?\s/)[0]),name=clean(metaName||heading).replace(new RegExp('^'+code+'\\s+'),''),place=header.match(/Plassering\s*:?\s*(.+)$/i)?.[1]||'',where=placement(place||groupYear||''),credits=section.slice(metaEnd).match(/^Studiepoeng\s*:\s*(\d+(?:[.,]\d+)?)/),type=header.match(/Type\s*:\s*(.+?)(?=\s+Plassering|$)/)?.[1]||'',choice=/^obligatorisk/i.test(type)?'O':group||/^valg/i.test(type)||/er et valgfritt emne/i.test(section.slice(0,400))?'V':'',sourcePage=documents.find(p=>text.indexOf(p.text)+p.text.length>anchor.index)?.page||1
    if(!name||!credits||+credits[1].replace(',','.')>240||explicitCode&&explicitCode!==code){warnings.push(`PDF-side ${sourcePage}: emnet ${code} har manglende eller motstridende metadata og er ikke normalisert.`);continue}
    if(seen.has(code)){warnings.push(`${code} har flere beskrivelser i samme kildeutgave. Første navngitte forekomst beholdes for uttrykkelig kontroll; ingen skjult sammenslåing av varianter.`);continue}seen.add(code)
    if(metaName&&heading&&!anchor[0].startsWith('Emne')&&normalize(heading)!==normalize(name)&&!normalize(heading).startsWith(normalize(name)+' ')&&!heading.includes('Læringsutbytte'))warnings.push(`${code}: overskriften «${heading}» og metadatafeltet «${metaName}» avviker. Begge er beholdt i kildenotatet og krever kontroll.`)
    const sourceNotes=`PDF-side ${sourcePage}. ${header}. Planutgave ${edition.academicYear}, ikke bekreftet opptakskull. Studiepoengene gjelder hele emnet${where.semesters.length>1?' over oppgitte semestre':''}. Velg bare emner som tilhører din retning og ditt semester.`
    courses.push({id:`onh-pdf:${selected.code}:${edition.academicYear}:${code}`,code,name,credits:Number(credits[1].replace(',','.')),choice,requiresSemesterChoice:true,semesters:where.semesters,sourceProvider:'onh-pdf',sourceRecordId:`${selected.code}:${code}`,sourceVersion:`studyplan:${edition.academicYear}`,sourceUrl:edition.sourceUrl,university:'Oslo Nye Høyskole',year:null,semester:null,campus:selected.campuses?.[0]||'',description:clean(section).slice(0,15000),notes:sourceNotes})
  }
  if(!courses.length)fail('not-supported','Denne publiserte PDF-en har ingen støttet emnebeskrivelse med navn, studiepoeng og semester-/typefelt. Ingen emner er utledet fra generell prosa.')
  const numbers=[...new Set([...courses.flatMap(c=>c.semesters),...text.matchAll(/\b(\d{1,2}\.|Første|Andre|Tredje|Fjerde|Femte|Sjette)\s*semester\b/gi)].flatMap(value=>Array.isArray(value)?placement(value[0]).semesters:[value]))].sort((a,b)=>a-b),periods=numbers.map(n=>({id:`semester-${n}`,studySemester:n,year:null,semester:null,label:`${n}. studiesemester · avklar kalender`,courses:courses.filter(c=>c.semesters.includes(n)).map(({semesters,...course})=>course),requirements:['Velg din faktiske retning og emner. Obligatorisk type i en emnebeskrivelse gjelder emnets kildekontekst, ikke automatisk alle retninger.']})),unplacedCourses=courses.filter(c=>!c.semesters.length).map(({semesters,...course})=>course)
  if(unplacedCourses.length)periods.push({id:'clarified',studySemester:null,requiresStudentStudySemester:true,year:null,semester:null,label:'Emner uten entydig studiesemester · avklar',courses:[],requirements:['Velg studiesemester uttrykkelig for kildens ufordelte emner.']})
  return{status:'ok',program:{...selected,cohort,cohortFromStudent:true,sourceUrl:edition.sourceUrl,sourceEdition:`${edition.academicYear} ${sourceEdition(text)}`},models:[{id:`pdf-${edition.academicYear.replace('/','-')}`,name:`Publisert PDF-utgave ${edition.academicYear} · velg retning/emner`,periods,unplacedCourses}],warnings:[...warnings,'Den publiserte studieårsutgaven er ikke et kullarkiv. Opptakskull og kalendersemester oppgis av studenten. Alle emner velges uttrykkelig, også kildeklassifiserte obligatoriske emner, fordi PDF-en kan beskrive flere retninger og tilbud.','Åpne valgemnekrav er ikke en full navngitt valgemneliste. Emnebeskrivelser og arbeidskrav er kildetekst; ingen dato, oppgave eller undervisning er opprettet fra dem.'],completeness:{complete:false,pages:pages.length,returned:courses.length,scope:'Alle støttede navngitte emnebeskrivelser i valgt faktisk PDF-utgave. Retninger, åpne valgkrav, kalender og studentkull krever eksplisitt avklaring.'}}
}
export async function onhPdfPlan(selected,query,{fetchText,fetchBytes}){const url=onhPdfUrl(query.sourceUrl),edition=(await onhPdfEditions(fetchText,selected)).find(row=>row.sourceUrl===url.href);if(!edition)fail('invalid-selection','Velg en kildepublisert PDF-utgave for akkurat dette programmet.');const guard=input=>{const candidate=onhPdfUrl(input);if(candidate.href!==edition.sourceUrl)fail('source-changed','PDF-kilden videresendte til en annen utgave.');return candidate};return parseOnhPdf(await readPublicPdfItems(fetchBytes,edition.sourceUrl,guard,{maxPages:200}),selected,edition,studentCohort(query))}
