import { clean, fail } from './program-source.js'
import { studentCohort, sourceEdition } from './current-program-source.js'

const tidy=value=>clean(value).replace(/\u00ad/g,'').replace(/\b([A-ZÆØÅ]{1,2})\s+([A-ZÆØÅ]{1,2})(?=\s*-\s*\d)/g,'$1$2').replace(/([–-])\s*(\d)\s+(\d)(?=\s*(?:sp|stp)\b)/gi,'$1 $2$3').replace(/\b([A-ZÆØÅ]{2,8})\s*-\s*((?:\d\s*){3}\d)(?:\s*-\s*(\d+))?/g,(_all,prefix,digits,suffix)=>`${prefix}-${digits.replace(/\s/g,'')}${suffix?`-${suffix}`:''}`).replace(/\b([A-ZÆØÅ]{2,8}-\d{4})-(\d+)\s*(?=(?:sp|stp|studiepoeng)\b)/gi,'$1 – $2 ').replace(/\bY\s*-\s*vei\b/gi,'Y-vei')
const codeRe=/\b([A-ZÆØÅ]{2,8}-\d{4}(?:-\d+)?)\b/g
function rows(items){const result=[];for(const item of [...items].sort((a,b)=>b.transform[5]-a.transform[5]||a.transform[4]-b.transform[4])){let row=result.find(row=>Math.abs(row.y-item.transform[5])<2);if(!row){row={y:item.transform[5],items:[]};result.push(row)}row.items.push(item)}return result.map(row=>({...row,items:row.items.sort((a,b)=>a.transform[4]-b.transform[4]),text:tidy(row.items.map(item=>item.str).join(' '))}))}
const period=number=>({id:`semester-${number}`,studySemester:number,year:null,semester:null,label:`${number}. studiesemester · avklar kalendersemester`,courses:[],requirements:[]})
const course=(record,info)=>({id:`uit-program:${info.record}:${record.code}`,code:record.code,name:record.name,credits:record.credits??null,choice:record.choice||'',year:null,semester:null,campus:record.campus||'',university:'UiT – Norges arktiske universitet',description:'',notes:record.notes,sourceProvider:'uit-program',sourceRecordId:record.code,sourceVersion:`pdf-${info.pdfId}`,sourceUrl:info.pdfUrl,...record.requiresSemesterChoice?{requiresSemesterChoice:true}:{}})
const sourceText=items=>rows(items).map(row=>row.text).join(' ')
function dictionary(pages){const found=new Map();for(const page of pages)for(const row of rows(page.items)){const matches=[...row.text.matchAll(codeRe)];if(matches[0]?.index!==0)continue;for(let i=0;i<matches.length;i++){const code=matches[i][1],text=clean(row.text.slice(matches[i].index+matches[i][0].length,matches[i+1]?.index??row.text.length));if(/^\s*[–—-]?\s*\d+(?:[.,]\d+)?\s*(?:sp|stp|studiepoeng)/i.test(text))continue;const name=clean(text.replace(/\s*\([^)]*(?:\)|$)/,'').replace(/\s*(?:\*|eller)\s*$/,''));if(name.length>3&&!/^(?:eller|\d|\*|\/)|valgf|Valgemne|Ingeniørfag\s*\*/i.test(name)&&!found.has(code))found.set(code,name)}}return found}

function matrixModels(pages,info,cohort){const models=[]
  for(const page of pages){const all=rows(page.items),header=all.find(row=>/Emnekode.*\bSP\b.*Emnenavn/.test(row.text));if(!header)continue
    const codeX=header.items.find(item=>item.str==='Emnekode')?.transform[4],nameX=header.items.find(item=>item.str==='Emnenavn')?.transform[4],creditX=header.items.find(item=>item.str==='SP')?.transform[4],semesterRow=all.find(row=>row.y<header.y&&/^1 2 3 4 5 6$/.test(row.text)),numbers=semesterRow?.items.filter(item=>/^\d+$/.test(item.str)).map(item=>({number:+item.str,x:item.transform[4]}))
    if(codeX===undefined||nameX===undefined||creditX===undefined||!numbers?.length)fail('source-changed','UiT-PDF-ens emne-/semesterkolonner er ikke entydige.')
    const above=all.filter(row=>row.y>header.y).map(row=>row.text).join(' '),cohortLabel=above.match(/B-[A-ZÆØÅ]+(20\d{2}|\d{2})\b\s*(og senere)?/),modelCohort=cohortLabel?(cohortLabel[1].length===2?2000:0)+Number(cohortLabel[1]):null
    if(modelCohort!==null&&(cohortLabel[2]?+cohort<modelCohort:+cohort!==modelCohort))continue
    const periods=numbers.map(row=>period(row.number)),anchors=all.filter(row=>row.y<semesterRow.y&&row.items.some(item=>item.transform[4]<creditX-2&&/^[A-ZÆØÅ]{2,8}-/.test(tidy(item.str)))),name=cohortLabel?`${cohortLabel[0]} · publisert semesterfordeling`:'Publisert semesterfordeling'
    for(let i=0;i<anchors.length;i++){const anchor=anchors[i],bottom=anchors[i+1]?.y??all.find(row=>row.y<anchor.y&&/^\*/.test(row.text))?.y??Math.min(...page.items.map(item=>item.transform[5])),items=page.items.filter(item=>item.transform[5]<=anchor.y+2&&item.transform[5]>bottom+2),rawCode=sourceText(items.filter(item=>item.transform[4]<creditX-2)),creditText=sourceText(items.filter(item=>item.transform[4]>=creditX-2&&item.transform[4]<nameX-2)),nameText=sourceText(items.filter(item=>item.transform[4]>=nameX-2&&item.transform[4]<numbers[0].x-3)),marks=numbers.filter(number=>items.some(item=>Math.abs(item.transform[4]-number.x)<4&&/^x$/i.test(item.str))),code=rawCode.replace(/\*/g,'').trim()
      if(!marks.length||!nameText||!/^\d+(?:[.,]\d+)?$/.test(creditText))fail('source-changed','UiT-PDF-en har en emnerad uten lesbart navn, studiepoeng eller semestermerke.')
      if(!new RegExp(`^${codeRe.source}$`).test(code)){for(const mark of marks)periods[mark.number-1].requirements.push(`Uavklart emnekode på PDF-side ${page.page}: ${rawCode} ${nameText} (${creditText} sp). Kilden samler flere kodealternativer; ingen kode er gjettet.`);continue}
      const campus=nameText.match(/Praksisprosjekt\s+(Tromsø|Hammerfest|Harstad|Narvik)(?=[\s,]|$)/)?.[1]||'',rotation=/\*/.test(rawCode),row=course({code,name:nameText,credits:Number(creditText.replace(',','.')),choice:campus?'V':'O',campus,requiresSemesterChoice:!!campus||rotation,notes:`PDF-side ${page.page}: ${rawCode} ${creditText} sp ${nameText}. ${name}. Kilden markerer studiesemester ${marks.map(mark=>mark.number).join(', ')}. Studiepoengene gjelder hele emnet.${rotation?' Praksisrullering: velg bare semesteret i din faktiske praksisplan.':''}${campus?' Campusspesifikt alternativ; velg bare ditt studiested.':''}`},info)
      for(const mark of marks)periods[mark.number-1].courses.push(row)
    }
    if(!periods.some(period=>period.courses.length))fail('source-changed','UiT-PDF-tabellen har ingen lesbare emner.')
    models.push({id:`matrix-${modelCohort||page.page}`,name,periods})
  }
  return models
}

function semesterModels(pages,info,names){const joined={items:pages.flatMap((page,index)=>page.items.map(item=>({...item,page:page.page,transform:item.transform.map((value,axis)=>axis===5?value-index*2000:value)})))},all=rows(joined.items),headers=all.filter(row=>row.items.some(item=>/^Semes$/.test(item.str))||row.items.some(item=>/^Semester$/i.test(item.str))&&/studiepoeng|\bstp\b/i.test(row.text)),models=[]
  for(let h=0;h<headers.length;h++){const header=headers[h],semesterX=header.items.find(item=>/^(Semester|Semes)$/i.test(item.str)).transform[4],bottomHeader=headers[h+1]?.y??-Infinity,above=all.filter(row=>row.y>header.y&&row.y<header.y+100),heading=above.map(row=>row.text.match(/Studieretning\s+[«"][^»"]+[»"]/)?.[0]).filter(Boolean).at(-1)||'Publisert semesterfordeling',sub=all.filter(row=>row.y<header.y&&row.y>bottomHeader),anchors=sub.filter(row=>row.items.some(item=>Math.abs(item.transform[4]-semesterX)<8&&/^(\d{1,2})(?:\.|\.\s*sem(?:ester)?)?$/i.test(tidy(item.str)))),periods=[]
    if(!anchors.length||anchors[0].items.find(item=>Math.abs(item.transform[4]-semesterX)<8)?.str.replace(/\D/g,'')!=='1')continue
    const maxRight=Math.max(...joined.items.map(item=>item.transform[4]+(item.width||0))),creditHeaders=header.items.flatMap((item,i)=>/^\d+\s+(?:studiepoeng|stp)$/i.test(item.str)?[{x:item.transform[4],credits:Number(item.str.match(/^\d+/)[0])}]:/^\d+$/.test(item.str)&&/^(?:studiepoeng|stp)$/i.test(header.items[i+1]?.str||'')?[{x:item.transform[4],credits:Number(item.str)}]:[])
    for(let index=0;index<anchors.length;index++){const anchor=anchors[index],number=Number(anchor.items.find(item=>Math.abs(item.transform[4]-semesterX)<8&&/^\d/.test(item.str)).str.match(/^\d+/)[0]);if(number!==index+1||number>40)fail('source-changed','UiT-PDF-tabellen hopper over eller gjentar et studiesemester.')
      let bottom=anchors[index+1]?.y??bottomHeader
      const section=sub.find(row=>row.y<anchor.y&&row.items.some(item=>item.transform[4]<semesterX-15&&!/^\d+$/.test(item.str))&&/Undervisnings|lærings|vurderings|Arbeidsomfang|Relevans/.test(row.text));if(section&&section.y>bottom)bottom=section.y
      const nextNotes=sub.find(row=>row.y<anchor.y&&/^\*|^\)\)|^\d+\)/.test(row.text));if(!anchors[index+1]&&nextNotes&&nextNotes.y>bottom)bottom=nextNotes.y
      const items=joined.items.filter(item=>item.transform[5]<=anchor.y+2&&item.transform[5]>bottom+2&&item.transform[4]>semesterX+15),seeds=items.filter(item=>/^[A-ZÆØÅ]{2,8}\s*-/.test(tidy(item.str))),columns=creditHeaders.length?creditHeaders.map(item=>item.x):seeds.map(item=>item.transform[4]).sort((a,b)=>a-b).filter((x,index,values)=>!index||x-values[index-1]>12),target=period(number),rowText=sourceText(items),allCreditCellsPresent=creditHeaders.length>0&&columns.every((x,i)=>items.some(item=>item.transform[4]>=x-12&&item.transform[4]<(columns[i+1]??maxRight+5)-12))
      if(!items.length)fail('source-changed','Et studiesemester i PDF-en mangler lesbart innhold.')
      if(/valgf|valg[ef]ag|spesialisering|ingeniørfag/i.test(rowText))target.requirements.push(`PDF-side ${anchor.items[0].page}: ${rowText}. Valg og spesialisering må avklares; ubestemte samleposter opprettes ikke som emner.`)
      for(let column=0;column<columns.length;column++){const x=columns[column],right=columns[column+1]??maxRight+5,tolerance=creditHeaders.length?12:2,cell=items.filter(item=>item.transform[4]>=x-tolerance&&item.transform[4]<right-tolerance),text=tidy(sourceText(cell)),matches=[...text.matchAll(codeRe)];if(!matches.length){if(/[A-ZÆØÅ]{2,8}-/.test(text))target.requirements.push(`Uleselig kode på PDF-side ${anchor.items[0].page}: ${text}`);continue}
        for(let c=0;c<matches.length;c++){const match=matches[c],code=match[1],end=matches[c+1]?.index??text.length,tail=clean(text.slice(match.index+match[0].length,end)),credit=tail.match(/(?:^\s*[–—-]?\s*|\()(\d+(?:[.,]\d+)?)\s*(?:sp\.?|stp\.?|studiepoeng)\b/i),optional=/\beller\b|valgf|valg[ef]ag/i.test(text),rawName=clean(tail.replace(/(?:^\s*[–—-]?\s*|\()\d+(?:[.,]\d+)?\s*(?:sp\.?|stp\.?|studiepoeng)\b\)?/i,'').replace(/\s*\b(?:eller|og)\s*$/i,'').replace(/\s*\/\s*$/,'')),name=names.get(code)||(!/valgf|valg[ef]ag|^\//i.test(rawName)&&rawName)||code,credits=credit?Number(credit[1].replace(',','.')):allCreditCellsPresent&&(matches.length===1||optional)?creditHeaders[column].credits:null
          if(target.courses.some(row=>row.code===code))continue
          target.courses.push(course({code,name,credits,choice:optional?'V':'O',notes:`PDF-side ${anchor.items[0].page}, ${number}. studiesemester: ${text}. ${name===code?'Emnenavnet mangler i denne tabellen; emnekoden er beholdt. ':''}${credits===null?'Hele emnets studiepoeng kan ikke leses entydig fra den sammenslåtte tabellcellen. ':''}${optional?'Velg bare emnet du faktisk følger.':''}`},info))
        }
      }
      periods.push(target)
    }
    if(periods.some(period=>period.courses.length)){
      const last=anchors.at(-1),after=sub.filter(row=>row.y<last.y),stop=after.findIndex(row=>/Studieretning\s+[«"]|Undervisnings|Arbeidsomfang|Relevans/.test(row.text)),footers=(stop<0?after:after.slice(0,stop)),start=footers.findIndex(row=>/Alternative ingeniørfag|Mulige (?:andre )?valgfag/i.test(row.text)),unplacedCourses=[]
      if(start>=0){const text=footers.slice(start).map(row=>row.text).join(' '),matches=[...text.matchAll(codeRe)];for(let i=0;i<matches.length;i++){const code=matches[i][1],tail=clean(text.slice(matches[i].index+code.length,matches[i+1]?.index??text.length)).replace(/^[\s,]+|[\s,]+$/g,''),name=names.get(code)||tail.split(/\s+\*|Studieretning/)[0].replace(/[,;]\s*$/,'')||code;if(unplacedCourses.some(row=>row.code===code))continue;unplacedCourses.push(course({code,name,credits:null,choice:'V',requiresSemesterChoice:true,notes:`Publiserte valgalternativer ved ${heading}, PDF-side ${footers[start].items[0].page}: ${text}. Kilden plasserer ikke dette alternativet entydig i ett studiesemester; velg bare faktiske emner som gjelder din plan.`},info))}for(const target of periods)if(target.requirements.some(text=>/valg|spesialiser/i.test(text)))target.requirements.push(`Kildens valgfagsmerknad: ${text}`)}
      models.push({id:`table-${h+1}`,name:heading,periods,unplacedCourses})
    }
  }
  return models
}
function studyYearModels(pages,info,names){const models=[]
  for(const page of pages){const all=rows(page.items),yearRows=all.filter(row=>row.items.filter(item=>/^\d+\.\s*studieår$/.test(item.str)).length>=2);if(!yearRows.length)continue
    for(let i=0;i<yearRows.length;i++){const anchor=yearRows[i],years=anchor.items.filter(item=>/^\d+\.\s*studieår$/.test(item.str)).map(item=>({number:Number(item.str.match(/^\d+/)[0]),center:item.transform[4]+item.width/2})),preceding=all.filter(row=>row.y>anchor.y&&row.y<anchor.y+90).map(row=>row.text).filter(text=>/Ordinær|Y-vei/.test(text)).at(-1),model={id:`year-table-${models.length+1}`,name:preceding||'Publisert årsfordeling',periods:[]};models.push(model)
      let bottom=yearRows[i+1]?.y??-Infinity;const stop=all.find(row=>row.y<anchor.y&&/Undervisnings|^Y-vei:/.test(row.text));if(stop&&stop.y>bottom)bottom=stop.y
      for(let y=0;y<years.length;y++){const {number,center}=years[y];if(number!==y+1)fail('source-changed','PDF-ens studieår mangler entydig rekkefølge.');const left=y?(years[y-1].center+center)/2:center-(years[1].center-center)/2,right=years[y+1]?(years[y+1].center+center)/2:center+(center-years[y-1].center)/2
      const items=page.items.filter(item=>item.transform[5]<anchor.y&&item.transform[5]>bottom+2&&item.transform[4]>=left&&item.transform[4]<right),text=tidy(items.map(item=>item.str).join(' ')),matches=[...text.matchAll(/\b([A-ZÆØÅ]{2,8}-[\dXx]{4}(?:-\d+)?)\b/g)],target={id:`year-${number}`,sourceStudyYear:number,studySemester:null,requiresStudentStudySemester:true,allowedStudySemesters:[number*2-1,number*2],year:null,semester:null,label:`${number}. studieår · oppgi studiesemester`,courses:[],requirements:[`Kilden viser studieår uten uttrykkelige semesteroverskrifter. Velg ${number*2-1}. eller ${number*2}. studiesemester og bare emnene som gjelder da; kalendersemester velges separat.`]}
      for(let c=0;c<matches.length;c++){const code=matches[c][1],tail=clean(text.slice(matches[c].index+code.length,matches[c+1]?.index??text.length)),credit=tail.match(/^\s*[–—-]?\s*(\d+(?:[.,]\d+)?)(?:\s*\+\s*(\d+(?:[.,]\d+)?))?\s*(?:sp|stp)\.?/i),credits=credit?Number(credit[1].replace(',','.'))+(credit[2]?Number(credit[2].replace(',','.')):0):null,rawName=clean(tail.slice(credit?.[0].length||0)),name=names.get(code)||rawName.replace(/Valgemner[\s\S]*$/i,'').trim()||code
        if(/[Xx]/.test(code)){target.requirements.push(`Ufullstendig emnekode på PDF-side ${page.page}: ${code} ${tail}. Koden er ikke opprettet som et emne.`);continue}if(target.courses.some(row=>row.code===code))fail('source-changed','Årsfordelingen gjentar et emne uten entydig deling.')
        target.courses.push(course({code,name,credits,choice:/3\s*-\s*sem/i.test(rawName)?'V':'',requiresSemesterChoice:true,notes:`PDF-side ${page.page}, ${number}. studieår (${model.name}): ${code} ${tail}. Studiesemester og studievei må velges uttrykkelig.${credit?.[2]?' Kilden oppgir delene med plusstegn; studiepoengene er summen for hele emnet.':''}`},info))
      }
      if(/Valgemner/i.test(text))target.requirements.push(`Kildens valgemnekrav: ${text.match(/Valgemner[\s\S]*/i)[0]}`)
      if(!target.courses.length)fail('source-changed','Et studieår i PDF-planen mangler lesbare emner.');model.periods.push(target)
      }
    }
  }
  return models
}
function namedOptions(pages,info,names){const result=[],requirements=[];let reading=false
  for(const page of pages)for(const row of rows(page.items)){if(/^Valgfri(?:e)?\s+emner\b/i.test(row.text)){reading=true;requirements.push(`Kildens valgkrav, PDF-side ${page.page}: ${row.text}`);continue}if(!reading)continue;if(/Andre emner kan|Tabell:|Oppbygging av|Ordinær|Undervisnings/i.test(row.text)){reading=false;continue}const match=row.text.match(/^([A-ZÆØÅ]{2,8}-[\dXx]{4}(?:-\d+)?)\s+(.+)$/);if(!match)continue;if(/[Xx]/.test(match[1])){requirements.push(`PDF-side ${page.page}: ${row.text}. Ufullstendig kode må avklares.`);continue}if(result.some(course=>course.code===match[1]))continue;const name=names.get(match[1])||match[2];result.push(course({code:match[1],name,choice:'V',credits:null,requiresSemesterChoice:true,notes:`Valgfritt emne i PDF-planen, side ${page.page}: ${row.text}. Studienes samlede valgfagsomfang er ikke studiepoeng for dette ene emnet. Velg studiesemester uttrykkelig.`},info))}
  return{courses:result,requirements}
}
export function parseUitPdf(pages,info,query){const cohort=studentCohort(query),cover=sourceText(pages[0]?.items||[]).replace(/Studie\s+plan/gi,'Studieplan').replace(/k\s+ull/gi,'kull').replace(/(20\d)\s+(\d)\b/g,'$1$2')
  if(!/studieplan/i.test(cover))fail('source-changed','Den lenkede PDF-en mangler en lesbar studieplanforside.')
  const from=info.label.match(/gjeldende fra (?:høsten |kull )?(20\d{2})/i)?.[1]||cover.match(/(?:Gjelder fra kull|Studiekull:)\s*(20\d{2})/i)?.[1],listed=info.label.match(/gjelder kull\s+(20\d{2})\s+og\s+(?:kull\s+)?(20\d{2})/i),exact=from||listed?null:cover.match(/\bKull\s+(?:B-[A-ZÆØÅ]+\s*)?(20\d{2})\b/i)?.[1]
  if(exact&&exact!==cohort||from&&+cohort<+from||listed&&!listed.slice(1).includes(cohort))fail('invalid-selection','Det oppgitte opptakskullet stemmer ikke med PDF-planens uttrykkelige kullgrense. Velg riktig planutgave.')
  const names=dictionary(pages),matrices=matrixModels(pages,info,cohort),semesters=matrices.length?[]:semesterModels(pages,info,names),models=matrices.length?matrices:semesters.length?semesters:studyYearModels(pages,info,names)
  if(!models.length){const imageTable=pages.some(page=>/Tabell:.*oppbygging av studieprogram/i.test(sourceText(page.items))&&sourceText(page.items).length<150);fail('not-supported',imageTable?'PDF-en har lesbar løpende tekst, men selve emnetabellen mangler lesbar tekst og kan være lagret som bilde. Lim inn tabellteksten eller registrer emnene manuelt; en eldre plan erstatter ikke denne utgaven.':'Denne UiT-PDF-en har ingen entydig støttet semesterfordeling for det valgte kullet. Bruk dokumentimport for å avklare tabellen; ingen annen planutgave er brukt.')}
  const optional=namedOptions(pages,info,names);for(const model of models){const placed=new Set(model.periods.flatMap(period=>period.courses.map(course=>course.code))),present=new Set(model.unplacedCourses?.map(course=>course.code)||[]);model.unplacedCourses??=[];for(const course of optional.courses)if(!placed.has(course.code)&&!present.has(course.code))model.unplacedCourses.push(course);for(const period of model.periods)if(period.requirements.some(text=>/valg/i.test(text)))period.requirements.push(...optional.requirements)}
  return{status:'ok',program:{code:query.program,name:info.name,sourceCode:info.studyCode,cohort,cohortFromStudent:true,sourceUrl:info.sourceUrl,sourceEdition:`pdf-${info.pdfId}:${sourceEdition(JSON.stringify(pages))}`,campuses:info.campuses||[]},models,warnings:[`Valgt kildeutgave: ${info.label}. Opptakskull er oppgitt av studenten${exact?` og samsvarer med PDF-forsiden (${exact})`:''}; kalendersemester må velges separat.`,models.some(model=>model.periods.some(period=>period.sourceStudyYear))?'Kilden fordeler emner på studieår, uten uttrykkelige semesteroverskrifter. Oppgi studiesemester og velg bare aktuelle emner; ingen semesterplassering er gjettet.':'Semesterfordelingen er lest fra PDF-en. Valgalternativer, campus og praksisrullering velges uttrykkelig.','Studiepoeng gjelder hele emnet; uklare sammenslåtte celler beholdes uten gjettet omfang.','Emnekoder uten navn i denne kildeutgaven vises med koden. Tidfestet undervisning, frister og personlige grupper er ikke utledet av studieplanen.'],completeness:{complete:false,pages:pages.length,returned:new Set(models.flatMap(model=>[...model.periods.flatMap(period=>period.courses),...(model.unplacedCourses||[])].map(row=>row.code))).size,reason:'Lesbare semester-/årstabeller i valgt PDF er importert. Kodealternativer, generelle valgkrav, sammenslåtte celler og praksis krever studentens kontroll.'}}
}
